// GENERATED by scripts/copy-transformers-ort.ts — do not hand-edit.
// SPDX-License-Identifier: MPL-2.0
// The same-origin base path of transformers.js's pinned onnxruntime-web wasm
// runtime (env.backends.onnx.wasm.wasmPaths in lib/speech-kokoro-worker.ts).
// Versioned so the SW's never-evicted cache-first /ort-hf/ bucket misses (and
// refetches) when a transformers.js upgrade ships a new runtime. Committed so
// tsc works on a fresh clone; regenerated by npm run build:ort.
export const ORT_HF_BASE = '/ort-hf/1.22.0-dev.20250409-89f8206ba4/';
