// SPDX-License-Identifier: MPL-2.0
/**
 * GENERATED by scripts/gen-shutter-mark.ts from the repo-root icon.svg —
 * do not edit by hand; run `npm run icons` after an icon change.
 *
 * The export shutter's Lolly mark, sliced in stacking order into static and
 * spinning layers. lib/shutter.ts stacks each slice in its own <div> and
 * tool.css rotates the DIVs (spin 1/2/3 = outer/mid/inner cadence) — HTML
 * transforms composite off the main thread, so the spin keeps turning while
 * the export render blocks it (SVG-child transforms, the old approach, froze).
 * The brand swirl reads var(--exsh-swirl), set per export by lib/shutter.ts.
 */

export interface ShutterMarkLayer {
  /** 0 = static; 1/2/3 = the outer/mid/inner spin cadence (tool.css). */
  readonly spin: 0 | 1 | 2 | 3;
  /** CSS blend for this slice's div — 'multiply' reproduces the icon's
   *  cross-layer swirl darkening at the STACKING level (see generator). */
  readonly blend: 'normal' | 'multiply';
  readonly svg: string;
}

export const SHUTTER_MARK_LAYERS: readonly ShutterMarkLayer[] = [
  { spin: 0, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm0-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm0-a"/>
    <radialGradient id="esm0-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm0-b"/>
    <radialGradient id="esm0-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm0-a"/>
    <radialGradient id="esm0-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm0-c"/>
    <radialGradient id="esm0-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm0-a"/>
    <radialGradient id="esm0-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm0-d"/>
    <radialGradient id="esm0-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm0-e"/>
    <radialGradient id="esm0-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <radialGradient id="esm0-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm0-g"/>
    <radialGradient id="esm0-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <radialGradient id="esm0-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm0-h"/>
    <radialGradient id="esm0-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm0-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <radialGradient id="esm0-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <radialGradient id="esm0-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm0-g"/>
    <linearGradient id="esm0-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm0-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm0-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm0-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm0-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm0-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm0-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <linearGradient id="esm0-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm0-j"/>
    <linearGradient id="esm0-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm0-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm0-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <linearGradient id="esm0-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm0-f"/>
    <filter id="esm0-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm0-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><path xmlns="http://www.w3.org/2000/svg" fill="url(#esm0-k)" d="M142.88 1.817A141.06 141.06 0 0 1 283.933 142.87 141.06 141.06 0 0 1 142.88 283.933 141.06 141.06 0 0 1 1.817 142.871 141.06 141.06 0 0 1 142.88 1.817" opacity=".3"/></g></svg>` },
  { spin: 1, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm1-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm1-a"/>
    <radialGradient id="esm1-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm1-b"/>
    <radialGradient id="esm1-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm1-a"/>
    <radialGradient id="esm1-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm1-c"/>
    <radialGradient id="esm1-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm1-a"/>
    <radialGradient id="esm1-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm1-d"/>
    <radialGradient id="esm1-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm1-e"/>
    <radialGradient id="esm1-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <radialGradient id="esm1-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm1-g"/>
    <radialGradient id="esm1-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <radialGradient id="esm1-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm1-h"/>
    <radialGradient id="esm1-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm1-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <radialGradient id="esm1-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <radialGradient id="esm1-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm1-g"/>
    <linearGradient id="esm1-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm1-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm1-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm1-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm1-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm1-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm1-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <linearGradient id="esm1-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm1-j"/>
    <linearGradient id="esm1-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm1-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm1-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <linearGradient id="esm1-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm1-f"/>
    <filter id="esm1-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm1-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g><path xmlns="http://www.w3.org/2000/svg" fill="url(#esm1-l)" d="M142.876 7.989A134.887 134.887 0 0 0 7.99 142.874 134.887 134.887 0 0 0 142.876 277.76a134.887 134.887 0 0 0 134.885-134.887A134.887 134.887 0 0 0 142.876 7.989"/></g></g></svg>` },
  { spin: 1, blend: 'multiply', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm2-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm2-a"/>
    <radialGradient id="esm2-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm2-b"/>
    <radialGradient id="esm2-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm2-a"/>
    <radialGradient id="esm2-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm2-c"/>
    <radialGradient id="esm2-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm2-a"/>
    <radialGradient id="esm2-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm2-d"/>
    <radialGradient id="esm2-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm2-e"/>
    <radialGradient id="esm2-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <radialGradient id="esm2-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm2-g"/>
    <radialGradient id="esm2-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <radialGradient id="esm2-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm2-h"/>
    <radialGradient id="esm2-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm2-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <radialGradient id="esm2-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <radialGradient id="esm2-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm2-g"/>
    <linearGradient id="esm2-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm2-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm2-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm2-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm2-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm2-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm2-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <linearGradient id="esm2-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm2-j"/>
    <linearGradient id="esm2-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm2-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm2-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <linearGradient id="esm2-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm2-f"/>
    <filter id="esm2-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm2-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g><path xmlns="http://www.w3.org/2000/svg" fill="var(--exsh-swirl, #008657)" d="M142.876 7.989a135 135 0 0 0-33.605 4.252A119.3 119.3 0 0 0 87.57 29.407a119.34 119.34 0 0 0-18.971 144.048 80.3 80.3 0 0 1-6.05-30.581 80.3 80.3 0 0 1 6.186-30.901A119.34 119.34 0 0 1 184 23.533a119.3 119.3 0 0 1 27.485 3.21A134.9 134.9 0 0 0 142.876 7.99m29.079 44.623a119.34 119.34 0 0 0-59.597 15.958 80.3 80.3 0 0 1 30.518-6.022 80.3 80.3 0 0 1 30.871 6.176 119.34 119.34 0 0 1 88.47 115.274 119.3 119.3 0 0 1-3.442 27.74 134.9 134.9 0 0 0 18.986-68.864 135 135 0 0 0-4.252-33.603 119.3 119.3 0 0 0-17.166-21.702 119.34 119.34 0 0 0-84.388-34.957M26.975 74.015a134.9 134.9 0 0 0-18.986 68.859 135 135 0 0 0 4.251 33.597 119.3 119.3 0 0 0 17.17 21.71 119.34 119.34 0 0 0 143.982 18.996 80.3 80.3 0 0 1-30.516 6.024 80.3 80.3 0 0 1-30.899-6.18 119.34 119.34 0 0 1-88.443-115.27 119.3 119.3 0 0 1 3.44-27.736m190.177 38.277a80.3 80.3 0 0 1 6.05 30.582 80.3 80.3 0 0 1-6.18 30.896 119.34 119.34 0 0 1-115.27 88.446 119.3 119.3 0 0 1-27.495-3.215 134.9 134.9 0 0 0 68.62 18.76 135 135 0 0 0 33.596-4.252 119.3 119.3 0 0 0 21.71-17.168 119.34 119.34 0 0 0 18.97-144.049" style=""/></g></g></svg>` },
  { spin: 0, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm3-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm3-a"/>
    <radialGradient id="esm3-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm3-b"/>
    <radialGradient id="esm3-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm3-a"/>
    <radialGradient id="esm3-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm3-c"/>
    <radialGradient id="esm3-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm3-a"/>
    <radialGradient id="esm3-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm3-d"/>
    <radialGradient id="esm3-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm3-e"/>
    <radialGradient id="esm3-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <radialGradient id="esm3-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm3-g"/>
    <radialGradient id="esm3-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <radialGradient id="esm3-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm3-h"/>
    <radialGradient id="esm3-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm3-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <radialGradient id="esm3-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <radialGradient id="esm3-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm3-g"/>
    <linearGradient id="esm3-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm3-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm3-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm3-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm3-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm3-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm3-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <linearGradient id="esm3-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm3-j"/>
    <linearGradient id="esm3-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm3-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm3-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <linearGradient id="esm3-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm3-f"/>
    <filter id="esm3-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm3-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><path xmlns="http://www.w3.org/2000/svg" fill="url(#esm3-m)" d="M142.878 52.084a90.793 90.793 0 0 1 90.788 90.788 90.793 90.793 0 0 1-90.788 90.794 90.793 90.793 0 0 1-90.794-90.794 90.793 90.793 0 0 1 90.794-90.788" opacity=".6"/></g></svg>` },
  { spin: 2, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm4-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm4-a"/>
    <radialGradient id="esm4-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm4-b"/>
    <radialGradient id="esm4-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm4-a"/>
    <radialGradient id="esm4-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm4-c"/>
    <radialGradient id="esm4-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm4-a"/>
    <radialGradient id="esm4-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm4-d"/>
    <radialGradient id="esm4-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm4-e"/>
    <radialGradient id="esm4-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <radialGradient id="esm4-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm4-g"/>
    <radialGradient id="esm4-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <radialGradient id="esm4-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm4-h"/>
    <radialGradient id="esm4-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm4-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <radialGradient id="esm4-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <radialGradient id="esm4-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm4-g"/>
    <linearGradient id="esm4-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm4-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm4-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm4-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm4-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm4-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm4-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <linearGradient id="esm4-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm4-j"/>
    <linearGradient id="esm4-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm4-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm4-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <linearGradient id="esm4-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm4-f"/>
    <filter id="esm4-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm4-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g><path xmlns="http://www.w3.org/2000/svg" fill="url(#esm4-n)" d="M220.464 163.666a80.326 80.326 0 0 1-98.378 56.799 80.326 80.326 0 0 1-56.801-98.379 80.326 80.326 0 0 1 98.381-56.8 80.326 80.326 0 0 1 56.798 98.38"/></g></g></svg>` },
  { spin: 2, blend: 'multiply', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm5-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm5-a"/>
    <radialGradient id="esm5-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm5-b"/>
    <radialGradient id="esm5-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm5-a"/>
    <radialGradient id="esm5-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm5-c"/>
    <radialGradient id="esm5-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm5-a"/>
    <radialGradient id="esm5-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm5-d"/>
    <radialGradient id="esm5-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm5-e"/>
    <radialGradient id="esm5-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <radialGradient id="esm5-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm5-g"/>
    <radialGradient id="esm5-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <radialGradient id="esm5-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm5-h"/>
    <radialGradient id="esm5-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm5-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <radialGradient id="esm5-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <radialGradient id="esm5-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm5-g"/>
    <linearGradient id="esm5-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm5-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm5-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm5-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm5-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm5-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm5-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <linearGradient id="esm5-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm5-j"/>
    <linearGradient id="esm5-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm5-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm5-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <linearGradient id="esm5-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm5-f"/>
    <filter id="esm5-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm5-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g><path xmlns="http://www.w3.org/2000/svg" fill="var(--exsh-swirl, #008657)" d="M214.185 179.852a57.95 57.95 0 0 0-6.56-40.723 57.95 57.95 0 0 0-41.68-28.346 39.53 39.53 0 0 1 15.935 25.722 57.95 57.95 0 0 1 9.428 49.505 57.95 57.95 0 0 1-24.153 33.435 80.33 80.33 0 0 0 47.03-39.593m5.271-60.873a80.33 80.33 0 0 0-39.607-47.415 57.95 57.95 0 0 0-40.72 6.56 57.95 57.95 0 0 0-28.218 41.504 39.53 39.53 0 0 1 25.618-15.716 57.95 57.95 0 0 1 49.481-9.47 57.95 57.95 0 0 1 33.446 24.537m-45.835 53.457a58 58 0 0 0 1.313-6.445 39.53 39.53 0 0 1-25.717 15.848 57.95 57.95 0 0 1-49.477 9.469 57.95 57.95 0 0 1-33.447-24.537 80.33 80.33 0 0 0 39.605 47.414 57.95 57.95 0 0 0 40.723-6.56 57.95 57.95 0 0 0 27-35.187zm-53.995 2.402a39.53 39.53 0 0 1-15.759-25.586v-.003a57.95 57.95 0 0 1-9.424-49.512 57.95 57.95 0 0 1 24.51-33.542 80.33 80.33 0 0 0-47.386 39.7 57.95 57.95 0 0 0 6.56 40.724 57.95 57.95 0 0 0 41.499 28.218z" style=""/></g></g></svg>` },
  { spin: 0, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm6-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm6-a"/>
    <radialGradient id="esm6-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm6-b"/>
    <radialGradient id="esm6-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm6-a"/>
    <radialGradient id="esm6-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm6-c"/>
    <radialGradient id="esm6-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm6-a"/>
    <radialGradient id="esm6-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm6-d"/>
    <radialGradient id="esm6-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm6-e"/>
    <radialGradient id="esm6-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <radialGradient id="esm6-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm6-g"/>
    <radialGradient id="esm6-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <radialGradient id="esm6-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm6-h"/>
    <radialGradient id="esm6-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm6-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <radialGradient id="esm6-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <radialGradient id="esm6-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm6-g"/>
    <linearGradient id="esm6-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm6-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm6-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm6-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm6-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm6-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm6-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <linearGradient id="esm6-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm6-j"/>
    <linearGradient id="esm6-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm6-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm6-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <linearGradient id="esm6-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm6-f"/>
    <filter id="esm6-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm6-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><path xmlns="http://www.w3.org/2000/svg" fill="url(#esm6-o)" fill-opacity=".8" d="M142.876 97.426a45.45 45.45 0 0 1 45.447 45.448 45.45 45.45 0 0 1-45.447 45.45 45.45 45.45 0 0 1-45.45-45.45 45.45 45.45 0 0 1 45.45-45.448"/></g></svg>` },
  { spin: 3, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm7-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm7-a"/>
    <radialGradient id="esm7-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm7-b"/>
    <radialGradient id="esm7-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm7-a"/>
    <radialGradient id="esm7-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm7-c"/>
    <radialGradient id="esm7-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm7-a"/>
    <radialGradient id="esm7-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm7-d"/>
    <radialGradient id="esm7-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm7-e"/>
    <radialGradient id="esm7-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <radialGradient id="esm7-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm7-g"/>
    <radialGradient id="esm7-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <radialGradient id="esm7-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm7-h"/>
    <radialGradient id="esm7-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm7-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <radialGradient id="esm7-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <radialGradient id="esm7-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm7-g"/>
    <linearGradient id="esm7-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm7-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm7-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm7-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm7-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm7-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm7-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <linearGradient id="esm7-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm7-j"/>
    <linearGradient id="esm7-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm7-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm7-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <linearGradient id="esm7-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm7-f"/>
    <filter id="esm7-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm7-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g><path xmlns="http://www.w3.org/2000/svg" fill="url(#esm7-p)" d="M142.876 103.35a39.525 39.525 0 0 1 39.523 39.524 39.525 39.525 0 0 1-39.523 39.525 39.525 39.525 0 0 1-39.526-39.525 39.525 39.525 0 0 1 39.526-39.524"/></g></g></svg>` },
  { spin: 3, blend: 'multiply', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm8-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm8-a"/>
    <radialGradient id="esm8-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm8-b"/>
    <radialGradient id="esm8-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm8-a"/>
    <radialGradient id="esm8-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm8-c"/>
    <radialGradient id="esm8-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm8-a"/>
    <radialGradient id="esm8-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm8-d"/>
    <radialGradient id="esm8-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm8-e"/>
    <radialGradient id="esm8-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <radialGradient id="esm8-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm8-g"/>
    <radialGradient id="esm8-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <radialGradient id="esm8-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm8-h"/>
    <radialGradient id="esm8-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm8-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <radialGradient id="esm8-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <radialGradient id="esm8-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm8-g"/>
    <linearGradient id="esm8-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm8-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm8-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm8-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm8-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm8-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm8-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <linearGradient id="esm8-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm8-j"/>
    <linearGradient id="esm8-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm8-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm8-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <linearGradient id="esm8-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm8-f"/>
    <filter id="esm8-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm8-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g><path xmlns="http://www.w3.org/2000/svg" fill="var(--exsh-swirl, #008657)" d="M143.838 104.576c-14.54 0-31.592 16.58-31.931 35.539-.224 12.526 9.73 20.413 19.465 20.413 20.155 0 21.919-14.145 21.919-18.848 0-9.613-12.162-11.825-12.162-3.21 0 4.667-12.846 10.84-12.846-2.182 0-9.75 11.538-19.213 19.751-19.213 11.798 0 25.836 8.958 25.836 26.755 0 23.815-31.731 33.97-44.53 36.18a39.5 39.5 0 0 0 13.536 2.39 39.525 39.525 0 0 0 39.523-39.526 39.53 39.53 0 0 0-18.314-33.348c-6.044-3.278-13.037-4.95-20.247-4.95" style=""/></g></g></svg>` },
  { spin: 0, blend: 'normal', svg: `<svg viewBox="0 0 285.75 285.75" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs xmlns="http://www.w3.org/2000/svg">
    <radialGradient id="esm9-k" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="matrix(4.6 0 0 4.6 -3908.588 -3116.499)" gradientUnits="userSpaceOnUse" href="#esm9-a"/>
    <radialGradient id="esm9-l" cx="880.759" cy="708.563" r="104.651" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm9-b"/>
    <radialGradient id="esm9-m" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-2464.807 -1954.987)scale(2.9607)" gradientUnits="userSpaceOnUse" href="#esm9-a"/>
    <radialGradient id="esm9-n" cx="880.759" cy="708.563" r="62.321" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.4)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm9-c"/>
    <radialGradient id="esm9-o" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-1162.495 -907.287)scale(1.4821)" gradientUnits="userSpaceOnUse" href="#esm9-a"/>
    <radialGradient id="esm9-p" cx="880.759" cy="708.563" r="30.665" fx="880.759" fy="708.563" gradientTransform="translate(-992.344 -770.401)scale(1.289)" gradientUnits="userSpaceOnUse" href="#esm9-d"/>
    <radialGradient id="esm9-q" cx="185.5" cy="140.06" r="21.959" gradientTransform="matrix(1.0274 -.2742 .4957 1.857 -99.417 -67.432)" gradientUnits="userSpaceOnUse" href="#esm9-e"/>
    <radialGradient id="esm9-r" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(.4818 0 0 .201 78.404 99.883)" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <radialGradient id="esm9-D" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm9-g"/>
    <radialGradient id="esm9-x" cx="134.04" cy="55.687" r="44.621" gradientTransform="rotate(105.09 157.873 118.132)scale(1.3426 .5601)" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <radialGradient id="esm9-A" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(1.6527 0 0 .6895 -82.307 -22.216)" gradientUnits="userSpaceOnUse" href="#esm9-h"/>
    <radialGradient id="esm9-h" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(3.3089 0 0 1.3804 -177.03 -56.743)" gradientUnits="userSpaceOnUse">
      <stop offset=".122" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="esm9-B" cx="134.04" cy="55.687" r="44.621" gradientTransform="matrix(-.7845 -.2551 .0877 -.3972 226.55 242.407)" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <radialGradient id="esm9-C" cx="142.79" cy="98.641" r="44.621" gradientTransform="matrix(-2.6758 -.8841 .2991 -1.3766 432.77 441.768)" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <radialGradient id="esm9-v" cx="133.578" cy="55.41" r="44.621" fx="107821.34" fy="29802.447" gradientTransform="matrix(2.0599 -.891 .3412 .7887 -25.845 190.825)" gradientUnits="userSpaceOnUse" href="#esm9-g"/>
    <linearGradient id="esm9-a">
      <stop offset="0" stop-opacity=".69"/>
      <stop offset=".837" stop-opacity=".673"/>
      <stop offset="1" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm9-b">
      <stop offset="0" stop-color="#e3e3e3"/>
      <stop offset=".875" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#6f6f6f"/>
    </linearGradient>
    <linearGradient id="esm9-c">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".768" stop-color="#f6f6f6"/>
      <stop offset="1" stop-color="#858585"/>
    </linearGradient>
    <linearGradient id="esm9-d">
      <stop offset="0" stop-color="#cacaca"/>
      <stop offset=".687" stop-color="#eaeaea"/>
      <stop offset="1" stop-color="#a6a6a6"/>
    </linearGradient>
    <linearGradient id="esm9-e">
      <stop offset=".476" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".654" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm9-f">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm9-s" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientTransform="translate(139.592 112.18)" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <linearGradient id="esm9-u" x1="297.634" x2="450.179" y1="324.622" y2="154.152" gradientTransform="translate(12.44 11.846)scale(.4785)" gradientUnits="userSpaceOnUse" href="#esm9-j"/>
    <linearGradient id="esm9-j">
      <stop offset=".087" stop-color="#fff" stop-opacity="0"/>
      <stop offset=".554" stop-color="#fff"/>
    </linearGradient>
    <linearGradient id="esm9-g">
      <stop offset=".308" stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="esm9-y" x1="-33.373" x2="-19.279" y1="49.632" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <linearGradient id="esm9-z" x1="-19.279" x2="-19.279" y1="48.713" y2="208.86" gradientUnits="userSpaceOnUse" href="#esm9-f"/>
    <filter id="esm9-t" width="1.018" height="1.01" x="-.009" y="-.005" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".375"/>
    </filter>
    <filter id="esm9-w" width="1.02" height="1.12" x="-.01" y="-.06" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation=".707"/>
    </filter>
  </defs><g><g xmlns="http://www.w3.org/2000/svg">
      <path fill="#fff" fill-opacity=".444" d="M131.581 119.013c-17.621 8.806-18.467 29.11-12.983 44.163 0 0-6.741-2.235-6.741-20.462 0-15.502 15.412-23.7 19.724-23.7z" opacity=".684"/>
      <path fill="url(#esm9-q)" d="M158.294 119.812c13.905 0 24.005 26.715 12.15 37.498 8.823-21.547-7.673-34.605-12.15-37.498" opacity=".494"/>
      <path fill="url(#esm9-r)" fill-opacity=".444" d="M163.05 115.707s-8.268-5.927-19.91-5.927-19.909 6.762-19.909 6.762 10.485-4.758 19.91-4.758c9.424 0 19.909 3.923 19.909 3.923"/>
      <path fill="url(#esm9-s)" d="M212.735 130.585c-123.2 51.227-102.44 162.38-100.15 166.35l21.568 27.29c-10.163-43.135-6.36-62.042-6.36-85.5 0-72.01 84.937-108.14 84.937-108.14z" filter="url(#esm9-t)" transform="translate(12.44 11.846)scale(.4785)"/>
      <path fill="url(#esm9-u)" d="M211.987 115.969c23.414 34.157-6.325 95.686-57.128 102.418 65.736-30.996 62.2-80.718 57.128-102.418" opacity=".494"/>
      <path fill="url(#esm9-v)" fill-opacity=".444" d="M355.01 135.555c-45.941-31.356-119.43-36.009-170.26 3.57 50.94-25.56 101.02-34.337 170.26-3.57" filter="url(#esm9-w)" transform="translate(12.44 11.846)scale(.4785)"/>
      <path fill="url(#esm9-x)" fill-opacity=".444" d="M209.038 212.75c32.284-25.97 43.187-68.525 21.882-109.076 9.557 43.266 9.755 70.988-21.882 109.077"/>
      <path fill="url(#esm9-y)" d="M67.321 28.209c-123.2 51.227-96.614 152.57-94.324 156.54l15.134 19.63c-4.355-18.482-29.268-128.29 79.19-176.17" filter="url(#esm9-t)" transform="translate(39.456 5.443)scale(.8626)"/>
      <path fill="url(#esm9-z)" d="M73.143 18.405c-123.2 51.227-102.44 162.38-100.15 166.35l15.134 19.63c-4.355-18.482-26.817-135.03 85.012-185.98Z" filter="url(#esm9-t)" opacity=".583" transform="rotate(-175.18 128.86 5.816)scale(.8043 -.8043)"/>
      <path fill="url(#esm9-A)" fill-opacity=".6" d="M208.089 32.072C171.23 6.915 112.267 3.182 71.486 34.936c40.87-20.506 81.053-27.548 136.603-2.864"/>
      <path fill="url(#esm9-B)" fill-opacity=".444" d="M95.604 166.306c14.297 20.182 41.813 31.435 65.21 19.436-22.009 5.505-41.98 3.36-65.21-19.436"/>
      <path fill="url(#esm9-C)" fill-opacity=".444" d="M48.515 167.45c20.164 66.683 72.786 86.511 134.404 63.66-66.198 1.174-101.815 7.328-134.404-63.66"/>
      <path fill="url(#esm9-D)" fill-opacity=".444" d="M355.01 135.555c-45.941-31.356-119.43-36.009-170.26 3.57 50.94-25.56 101.02-34.337 170.26-3.57" filter="url(#esm9-w)" transform="translate(12.44 11.846)scale(.4785)"/>
    </g></g></svg>` },
];
