// SPDX-License-Identifier: MPL-2.0
// GENERATED from plans/component-audit.md (the component-audit workflow synthesis).
// Do not hand-edit specimen data here; edit the audit + regenerate. The VIEW
// (views/components.ts) supplies the live renderers keyed by `live`.
export interface Specimen {
  name: string; defined?: string; description?: string;
  kind: 'pure-html-fn' | 'wired-fn' | 'markup-only' | 'needs-host';
  css?: string; eg?: string[];
  live?: string;      // key into the view's LIVE_RENDERERS
  markup?: string;    // static HTML sample
  code?: string;      // source snippet, when neither live nor previewable
}
export interface Section { group: 'common' | 'view'; title: string; blurb?: string; items: Specimen[] }

export const AUDIT_SECTIONS: Section[] = [
  { group: "common", title: "Buttons", items: [
    { name: "Studio buttons (.be-cta / .be-btn)", defined: "shells/web/src/lib/brand-editor.ts:678 / styles/parts/brand-studio.css:17", description: "Filled primary (.be-cta) + outline secondary (.be-btn), --sm size, glossy .is-active apply state. De-facto primary/ghost pair app-wide.", kind: "markup-only", css: ".be-cta, .be-btn, .be-btn--sm, .be-cta.is-active", eg: ["Use this colour","Cancel","+ Add","Apply palette"], markup: `<button class="be-cta">Use this colour</button> <button class="be-btn">Cancel</button> <button class="be-btn be-btn--sm">+ Add</button> <button class="be-cta is-active">Apply palette</button>` },
    { name: "Ghost nav button (.nav-btn)", defined: "shells/web/src/styles/parts/base.css:131", description: "Transparent text button filling with --accent on hover; --active bolds and keeps the fill.", kind: "markup-only", css: ".nav-btn, .nav-btn--active", eg: ["Tools","Catalog (active)"], markup: `<button class="nav-btn">Tools</button> <button class="nav-btn nav-btn--active">Catalog</button>` },
    { name: "Back-home pill (.tools-home)", defined: "shells/web/src/styles/parts/components.css:135", description: "Tinted primary pill with a leading arrow, the 'Tools' back link; .sidebar-back stops it stretching.", kind: "markup-only", css: ".tools-home, .tools-home.sidebar-back", eg: ["Tools"], markup: `<a href="#/" class="tools-home">Tools</a>` },
    { name: "Filter / count pill (.gallery-pill)", defined: "shells/web/src/styles/parts/gallery.css:593", description: "Outline chip-button filling with --primary when .active; .ct dims a trailing count, --fav leads with a star.", kind: "markup-only", css: ".gallery-pill, .gallery-pill--fav, .gallery-pill.active, .pill-star, .ct", eg: ["Brand 12","Favourites (star)","All active"], markup: `<button class="gallery-pill active">Brand <span class="ct">12</span></button> <button class="gallery-pill gallery-pill--fav"><span class="pill-star">★</span>Favourites</button>` },
  ] },
  { group: "common", title: "Segmented controls", items: [
    { name: "Segmented control (canonical .view-seg)", defined: "shells/web/src/styles/parts/gallery.css:508 / brand-editor.ts:268 (segHtml)", description: "Flex row of equal-width outline buttons; aria-pressed=true fills --primary. Base for brand studio's .be-seg wrap modifier. THE target for unifying all segmented controls.", kind: "pure-html-fn", css: ".view-seg, .view-seg-btn, .be-seg", eg: ["Gallery","Cover Flow","Mono","Complement"], markup: `<div class="view-seg" role="group"><button class="view-seg-btn" aria-pressed="true">Gallery</button><button class="view-seg-btn" aria-pressed="false">Cover Flow</button></div>` },
    { name: "Segmented control (storage duplicate)", defined: "shells/web/src/styles/parts/storage.css:350", description: "DUPLICATE of .view-seg: joined buttons in one bordered trough with dividers, uppercase, aria-pressed. Merge into .view-seg.", kind: "markup-only", css: ".segmented-control, .segmented-btn", eg: ["By type","By tool"], markup: `<div class="segmented-control"><button class="segmented-btn" aria-pressed="true">By type</button><button class="segmented-btn" aria-pressed="false">By tool</button></div>` },
    { name: "Dashboard tab bar (.dash-tabs)", defined: "shells/web/src/styles/parts/dashboard.css:40 / views/dashboard.ts:96", description: "Pill tabs in a muted trough; .is-active lifts to a --card pill (uses .is-active, not aria). Third active convention.", kind: "markup-only", css: ".dash-tabs, .dash-tab, .dash-tab.is-active, .dash-tab-icon", eg: ["Overview","This device","Design system"], markup: `<div class="dash-tabs" role="tablist"><button class="dash-tab is-active" role="tab">Design system</button><button class="dash-tab" role="tab">Capabilities</button></div>` },
    { name: "Colour-space mode tabs (.color-mode-tabs)", defined: "shells/web/src/styles/parts/components.css:349", description: "Pill tabs in a 999px trough; the active tab gets the bold pill (aria-selected). OKLCH is the default. Near-identical to .dash-tabs — fourth active convention.", kind: "markup-only", css: ".color-mode-tabs, .color-mode-tab", eg: ["HEX","OKLCH","HSL","RGB"], markup: `<div class="color-mode-tabs"><button class="color-mode-tab" aria-selected="false">HEX</button><button class="color-mode-tab" aria-selected="true">OKLCH</button><button class="color-mode-tab" aria-selected="false">RGB</button></div>` },
    { name: "Stored-as segment (.be-stored-seg)", defined: "shells/web/src/lib/brand-editor.ts:802", description: "Bespoke aria-pressed group choosing a swatch's storage notation. Does NOT reuse .view-seg despite being visually identical.", kind: "markup-only", css: ".be-stored, .be-stored-seg, [data-store-fmt]", eg: ["LCH","Hex","RGB"], markup: `<div class="be-stored-seg" role="group"><button data-store-fmt="lch" aria-pressed="true">LCH</button><button data-store-fmt="hex" aria-pressed="false">Hex</button></div>` },
    { name: "View toggle (Tools/Projects/Catalog)", defined: "shells/web/src/components/view-toggle.ts:28", description: "Three hash-link tabs, icon+label; label hides on mobile. Pure markup, router handles nav. Uses .is-active.", kind: "pure-html-fn", css: ".view-toggle, .view-toggle-opt, .is-active, .view-toggle-ic, .view-toggle-label", eg: ["tools","projects","catalog"], live: "viewToggle" },
    { name: "Theme segmented control (host-free html)", defined: "shells/web/src/components/theme-toggle.ts:75", description: "Light/Dark/Brand as a .view-seg group with a section head; wireThemeSegment persists to profile.", kind: "pure-html-fn", css: ".view-seg, .view-seg-btn, .filter-pop-head", eg: ["Light","Dark","Brand"], live: "themeSeg" },
  ] },
  { group: "common", title: "Chips / badges / pills", items: [
    { name: "Micro-badge / stat / secondary chip (.plat-*)", defined: "shells/web/src/styles/parts/platform.css:146", description: "Family of platform chips: .plat-pill status badge (+--muted), .plat-stat number+label pill, .plat-chip low-emphasis label. Core of the chip-naming sprawl.", kind: "markup-only", css: ".plat-pill, .plat-pill--muted, .plat-stat, .plat-chip", eg: ["Default","13 tools","experimental"], markup: `<span class="plat-pill">Default</span> <span class="plat-stat"><strong>13</strong> tools</span> <span class="plat-chip">experimental</span>` },
    { name: "Count bubble (.cat-group-count = .plat-ramp-count)", defined: "shells/web/src/styles/parts/components.css:45 / platform.css", description: "Small 999px --muted number bubble next to a group title. The two classes are BYTE-IDENTICAL — merge.", kind: "markup-only", css: ".cat-group-count, .plat-ramp-count", eg: ["7","12","3"], markup: `<h3 class="cat-group-title">Utilities <span class="cat-group-count">7</span></h3>` },
    { name: "Icon status tag (.cat-tag)", defined: "shells/web/src/styles/parts/components.css:90", description: "Rounded --muted chip with a leading icon and a bold count; shared by catalog-summary.", kind: "markup-only", css: ".cat-tags, .cat-tag, .cat-tag-icon", eg: ["3 stable","2 experimental"], markup: `<span class="cat-tag"><span class="cat-tag-icon"></span><strong>3</strong> stable</span>` },
    { name: "Tile output-spec badges", defined: "shells/web/src/folder-tiles.ts:98", description: "The small chips beneath a tile title: format, canvas size, batch rows, byte size. Mirrors the gallery card badges.", kind: "pure-html-fn", css: ".tile-badge, .tile-badge--fmt, .tile-badge--rows, .tile-badge--size", eg: ["SVG","512×512 px","8 rows","20 KB"], live: "tileBadges" },
    { name: "Gen-AI provenance pill", defined: "shells/web/src/lib/genai-pill.ts:37 / styles/parts/catalog.css:202", description: "Fixed-violet 'Gen AI' pill (brand-independent, --vf-ai-*) flagging AI content; collapses to a sparkle circle.", kind: "pure-html-fn", css: ".genai-pill, .genai-pill--icon, .genai-pill-lbl", eg: ["Gen AI (full)","icon-only circle"], live: "genai" },
    { name: "Made-with-Lolly badge", defined: "shells/web/src/lib/lolly-badge.ts:19 / styles/parts/catalog.css:551", description: "Lollipop glyph + 'Made with Lolly' wordmark lockup, shown only for a genuine Lolly export credential.", kind: "pure-html-fn", css: ".lolly-badge, .lolly-badge--sm, .lolly-badge--lg", eg: ["sm inline","lg lockup"], live: "lollyBadge" },
  ] },
  { group: "common", title: "Cards / panels / surfaces", items: [
    { name: "Section card (.plat-section) — canonical", defined: "shells/web/src/styles/parts/platform.css:68", description: "Collapsible <details> --card panel with a rotating-chevron summary. The de-facto canonical surface; dashboard reuses it as .dash-collapse.", kind: "markup-only", css: ".plat-section, .plat-section-summary, .plat-section-title, .plat-section-chev, .plat-section-body", eg: ["Palette (open)","Storage (folded)"], markup: `<details class="plat-section" open><summary class="plat-section-summary"><span class="plat-section-title">Palette</span><span class="plat-section-chev">›</span></summary><div class="plat-section-body">…</div></details>` },
    { name: "Studio panel (.be-panel)", defined: "shells/web/src/lib/brand-editor.ts:630 / styles/parts/brand-studio.css:10", description: "The editor's --card panel with a titled head + muted sub; base surface for every .be-* control group.", kind: "markup-only", css: ".be-panel, .be-panel-head, .be-panel-title, .be-panel-sub, .be-err", eg: ["Colour","Fonts","Tokens"], markup: `<section class="be-panel"><div class="be-panel-head"><h3 class="be-panel-title">Colour</h3><p class="be-panel-sub">Pick one colour.</p></div></section>` },
    { name: "Nested sub-card (.plat-client-card / .plat-font / .plat-theme)", defined: "shells/web/src/styles/parts/platform.css:202", description: "--background bordered sub-panel with an uppercase icon head; repeated as font/theme/capability cards.", kind: "markup-only", css: ".plat-client-card, .plat-client-title, .plat-font, .plat-theme, .cap-card", eg: ["Display","font specimen","theme swatch"], markup: `<div class="plat-client-card"><h4 class="plat-client-title"><span class="plat-client-icon"></span>Display</h4><dl class="plat-kv"><div><dt>Resolution</dt><dd>2560×1440</dd></div></dl></div>` },
    { name: "Icon count tile (.cat-tile)", defined: "shells/web/src/lib/catalog-summary.ts:102 / styles/parts/components.css:78", description: "Even-grid stat tile: glyph + big count + type label. NOTE .cat-tile also names an asset card in catalog.ts — class collision.", kind: "pure-html-fn", css: ".cat-grid, .cat-tile, .cat-tile-icon, .cat-tile-num, .cat-tile-label, .cat-tags", eg: ["22 Logos","8 Fonts"], live: "catSummary" },
    { name: "Page header band (.plat-header)", defined: "shells/web/src/styles/parts/platform.css:7", description: "Standard view header: clamped title + sub. One of three header patterns (.start-head, .be-panel-head).", kind: "markup-only", css: ".plat-header, .plat-title, .plat-sub, .plat-header-text", eg: ["This build","Everything that ships…"], markup: `<header class="plat-header"><h1 class="plat-title">This build</h1><div class="plat-header-text"><p class="plat-sub">Everything that ships in this install.</p></div></header>` },
    { name: "Key/value list (.plat-kv) + data table (.plat-table)", defined: "shells/web/src/styles/parts/platform.css:167 / :141", description: "Definition-list grid with --wide/.is-mono/.is-hero modifiers, plus the bordered-row reference table with .is-default.", kind: "markup-only", css: ".plat-kv, .is-hero, .is-mono, .plat-table, .plat-table tr.is-default", eg: ["Storage 1.4 GB","Format png (Default)"], markup: `<dl class="plat-kv"><div class="is-hero"><dt>Storage</dt><dd class="is-hero">1.4 GB</dd></div></dl>` },
  ] },
  { group: "common", title: "Inputs / fields / sliders", items: [
    { name: "Sidebar input row (.input-row)", defined: "shells/web/src/views/tool-inputs.ts:292", description: "Label + control wrapper every declared input renders into; label for simple, role=group for composites.", kind: "markup-only", css: ".input-row, .input-row--checkbox, .input-label, .input-value, .is-target", eg: ["Headline text","checkbox","slider row"], markup: `<label class="input-row"><span class="input-label"><span class="input-label-text">Headline</span></span><input type="text" data-input-id="headline" value="Hello"></label>` },
    { name: "Custom slider (.custom-slider)", defined: "shells/web/src/views/tool-inputs.ts:1247", description: "Pointer/keyboard range with fill, thumb, optional ticks and live readout.", kind: "markup-only", css: ".custom-slider, .cs-track, .cs-fill, .cs-thumb, .cs-ticks, .cs-tick", eg: ["0%","50% w","ticks","100%"], markup: `<div class="custom-slider" role="slider" aria-valuenow="50"><div class="cs-track"><div class="cs-fill" style="width:50%"></div><div class="cs-thumb" style="left:50%"></div></div></div>` },
    { name: "Colour value field (.color-input painted)", defined: "shells/web/src/styles/parts/components.css:392", description: "Large centred mono field painting itself the current colour over a checkerboard, inset eyedropper.", kind: "markup-only", css: ".color-input-wrap, .color-input, .color-input--painted, .color-eyedropper", eg: ["#3B82F6 painted","translucent checker"], markup: `<div class="color-input-wrap"><button class="color-eyedropper"><svg></svg></button><input class="color-input color-input--painted" style="--color-input-bg:#3b82f6;--color-input-fg:#fff" value="#3B82F6"></div>` },
    { name: "Mono text input recipe (.be-fmt-input family)", defined: "shells/web/src/styles/parts/brand-studio.css:334", description: "The small mono text input (--input border, --background, .5x radius, --ring focus) re-implemented as .be-lock-field/.be-cmyk-in/.share-link-field. Candidate .field-input.", kind: "markup-only", css: ".be-fmt-input, .be-lock-field, .be-cmyk-in, .share-link-field", eg: ["#00A98F","CMYK 80","readonly link"], markup: `<input class="be-fmt-input" value="#00A98F"> <input class="be-cmyk-in" value="80">` },
    { name: "Custom axis slider (.color-lch-slider = .color-mode-slider)", defined: "shells/web/src/styles/parts/components.css:628", description: "appearance:none range with an inline oklch() axis-gradient track and white ring thumb; thumb rules duplicated across the two class names.", kind: "markup-only", css: ".color-lch-slider, .color-mode-slider, .color-lch-val, .is-clamped", eg: ["L","C","H rows"], markup: `<div class="color-lch-row"><span class="color-lch-label">L</span><input type="range" class="color-lch-slider" style="background:linear-gradient(90deg,#000,#fff)"><span class="color-lch-val">72%</span></div>` },
    { name: "Accent range slider (.brand-radius-slider family)", defined: "shells/web/src/styles/parts/brand-studio.css:58", description: "Plain native range using accent-color:--primary (radius/shades) or --ring (alpha), with a mono value readout.", kind: "markup-only", css: ".brand-radius-slider, .be-steps-slider, .color-alpha-slider", eg: ["radius 0.5rem","shades 9","alpha %"], markup: `<div class="brand-radius-row"><span class="brand-radius-preview"></span><input type="range" class="brand-radius-slider"><span class="brand-radius-value">0.5rem</span></div>` },
    { name: "Vector input (scrub fields)", defined: "shells/web/src/views/tool-inputs.ts:1643", description: "N number sub-fields committed as one object; each has a drag-scrub char handle. Rendered 3 ways (.vec-* sidebar, .pro-vec-* pro).", kind: "markup-only", css: ".vector-input, .vec-field, .vec-scrub, .vec-num", eg: ["X","Y pair","zoom+pos+scale trio"], markup: `<div class="vector-input" data-input-id="offset"><span class="vec-field"><span class="vec-scrub" data-vec-scrub="x">X</span><input type="number" class="vec-num" data-vec-field="x" value="0"></span></div>` },
  ] },
  { group: "common", title: "Dialogs / modals & toasts", items: [
    { name: "Modal dialog (confirm / choice / notice / prompt)", defined: "shells/web/src/components/confirm-dialog.ts:24", description: "One native <dialog> chrome (.projects-confirm) with four content shapes. Closest thing to a modal primitive — should absorb share/welcome/profile hand-rolled dialogs.", kind: "wired-fn", css: ".projects-confirm, .projects-confirm-title, .projects-confirm-actions, .projects-confirm-primary, .projects-confirm-danger", eg: ["Delete confirm (danger)","3-way choice","notice","password prompt"], live: "dialogTriggers" },
    { name: "Share-link dialog", defined: "shells/web/src/components/share-dialog.ts:114", description: "Copy-ready share URL + on-visit toggles, shortest-link pack, optional AES password. Hand-rolls its own <dialog> lifecycle.", kind: "wired-fn", css: ".share-dialog, .share-link-row, .share-copy-btn, .share-toggles, .share-warning", eg: ["plain link + toggles","password-protect expanded"], live: "shareTrigger" },
    { name: "Toast", defined: "shells/web/src/styles/parts/tool-chrome.css:8", description: "Bottom-centre frosted 999px pill toast, icon+message+optional action. .is-visible slides in.", kind: "markup-only", css: ".toast, .toast.is-visible, .toast-icon, .toast-message, .toast-action, .toast.is-muted", eg: ["Copied link","with Undo action"], markup: `<div class="toast is-visible"><span class="toast-icon"></span><span class="toast-message">Copied link</span><button class="toast-action">Undo</button></div>` },
    { name: "Progress toast (.pro-toast)", defined: "shells/web/src/views/multi-edit.ts:516", description: "Floating toast hosting an offscreen render pipeline's progress UI. Same component under two names: .pro-toast--top (profile) and .projects-toast (projects/multi-edit).", kind: "markup-only", css: ".pro-toast, .projects-toast, .pro-toast--top, .pro-toast-close, .pro-toast-mount, .pro-progress-msg", eg: ["rendering…","error","closable"], markup: `<div class="pro-toast projects-toast"><button class="pro-toast-close">✕</button><div class="pro-toast-mount"></div></div>` },
    { name: "Unsaved-changes dialog", defined: "shells/web/src/pro/index.ts:1427 / styles/parts/dialogs.css:3", description: "Leave-guard modal: Save & leave / Leave without saving / Cancel. Mirrored in tool view leave-guard.", kind: "markup-only", css: ".unsaved-dialog, .unsaved-save, .unsaved-leave, .unsaved-cancel", eg: ["3 buttons","save-in-progress"], markup: `<div class="unsaved-dialog"><button class="unsaved-save">Save &amp; leave…</button><button class="unsaved-leave">Leave without saving</button><button class="unsaved-cancel">Cancel</button></div>` },
  ] },
  { group: "common", title: "Toggles & switches", items: [
    { name: "Sound switch (labelled sliding toggle)", defined: "shells/web/src/components/sound-toggle.ts:134", description: "Speaker + 'Sound:' label + role=switch sliding knob; self-injects CSS. The only real switch primitive; optional Neurospicy sub-switch.", kind: "pure-html-fn", css: ".sound-switch, .sound-switch-track, .sound-switch-knob, .neurospicy, .neuro-show-btn", eg: ["sound on (knob right)","off","with Neurospicy"], live: "soundSwitch" },
    { name: "Sound icon toggle (stage-nav)", defined: "shells/web/src/components/sound-toggle.ts:63", description: "Icon-only speaker on/off for the zoom HUD; persists sfxMuted to profile.", kind: "needs-host", css: ".stage-nav-btn, .stage-nav-sound", eg: ["on (waves)","off (muted)"], code: "import { createSoundToggle } from '../components/sound-toggle.ts'; createSoundToggle(host) // returns HTMLButtonElement" },
    { name: "Theme cycle toggle (icon button)", defined: "shells/web/src/components/theme-toggle.ts:31", description: "Compact icon-only button stepping light→dark→brand; persists to profile. One of ~4 theme UIs.", kind: "needs-host", css: ".stage-nav-btn, .stage-nav-theme", eg: ["light","dark","brand glyph"], code: "import { createThemeToggle } from '../components/theme-toggle.ts'; createThemeToggle(host) // returns HTMLButtonElement" },
    { name: "Feature-flag switch (.feature-flag-switch)", defined: "shells/web/src/views/profile.ts:202", description: "iOS-style sliding switch with optional pill and an (i) info popover; separate from .sound-switch.", kind: "markup-only", css: ".feature-flag, .feature-flag-switch, .feature-flag-input, .feature-flag-pill, .feature-flag-info-btn", eg: ["on","off","with Beta pill","with (i)"], markup: `<label class="feature-flag"><span class="feature-flag-label">Neurospicy Mode<span class="feature-flag-pill">Beta</span></span><input type="checkbox" class="feature-flag-input" checked><span class="feature-flag-switch"></span></label>` },
    { name: "Export option chip (.export-option)", defined: "shells/web/src/views/tool-actions.ts:434", description: "Reusable labelled checkbox chip for boolean export settings (transparent, convert paths, dither, 60fps, marks).", kind: "markup-only", css: ".export-option, .export-settings, data-vector-only, data-html-only", eg: ["Transparent","Convert paths","Dither"], markup: `<label class="export-option"><input type="checkbox" data-action="gif-dither"> Dither</label>` },
  ] },
  { group: "common", title: "Tooltips, notes & callouts", items: [
    { name: "Help tip (info button + popover)", defined: "shells/web/src/components/help-tip.ts:39", description: "Small (i) button + hover/tap/focus-revealed pop with optional action link; aria-describedby. The intended shared 'i' affordance (profile .info-dot and .feature-flag-info-btn duplicate it).", kind: "wired-fn", css: ".help-tip-btn, .help-tip-pop, .help-tip-link, .help-tip-host", eg: ["text only","with 'Check a file' link"], live: "helpTip" },
    { name: "Scrub readout bubble", defined: "shells/web/src/components/scrub-readout.ts:71", description: "One reusable fixed bubble showing the live value during a drag-scrub, anchored above a control or the fingertip.", kind: "wired-fn", css: ".scrub-readout, .is-visible, .is-below", eg: ["'480 px' anchored","finger-tracked"], code: "import { showScrubReadout, hideScrubReadout } from '../components/scrub-readout.ts'; showScrubReadout({ text:'480 px', finger:{ x:200, y:300 } })" },
    { name: "Note / error / callout boxes", defined: "shells/web/src/styles/parts/platform.css:12 / components.css:16", description: "Near-identical muted/tinted bordered callouts: .plat-note, .error(+.error-list), .share-note, .share-warning, .valid-note. Candidate single .note.", kind: "markup-only", css: ".plat-note, .error, .error-list, .share-note, .share-warning, .valid-note", eg: ["info note","error w","list"], markup: `<p class="plat-note"><strong>Note.</strong> Everything renders on-device — nothing is uploaded.</p> <div class="error">Couldn't render this tool.<ul class="error-list"><li>Missing <code>url</code></li></ul></div>` },
    { name: "Swatch-name tooltip", defined: "shells/web/src/styles/parts/components.css:733", description: "Body-fixed pointer-events:none tooltip painted in the hovered swatch's own colour.", kind: "markup-only", css: ".swatch-name-tip, .swatch-name-tip.is-shown", eg: ["'Persimmon 3' shown"], markup: `<div class="swatch-name-tip is-shown" style="background:#e0542a;color:#fff;left:120px;top:80px">Persimmon 3</div>` },
    { name: "On-device privacy badge", defined: "shells/web/src/styles/parts/tool.css:1960", description: "Primary-tinted bordered banner reassuring the file never leaves the device; --float overlays the editor.", kind: "markup-only", css: ".on-device-badge, .on-device-badge--float", eg: ["inline banner","--float overlay"], markup: `<div class="on-device-badge"><svg viewBox="0 0 24 24"></svg> Runs on your device</div>` },
  ] },
  { group: "common", title: "Colour tools", items: [
    { name: "Colour field (swatch trigger + OKLCH popover)", defined: "shells/web/src/components/color-field.ts:480", description: "The one colour control: swatch+name trigger opening a hex field + eyedropper, conic OKLCH dials, L/C/H sliders or mode tabs, alpha, lazy palette grid. Reused everywhere.", kind: "wired-fn", css: ".color-picker-field, .color-trigger, .color-popover, .color-dials, .color-lch, .color-mode-tab, .color-field--inline", eg: ["#e11d48 named","OKLCH dials","inline panel","transparent"], live: "colorField" },
    { name: "Read-only swatch card (swatch())", defined: "shells/web/src/lib/swatches.ts:70", description: "Brand-colour chip: click-to-copy, name, hex, CMYK/SPOT readout + flag when print-locked. One of 4 swatch-tile renderings (rec 12).", kind: "pure-html-fn", css: ".plat-swatch, .plat-swatch-chip, .plat-swatch-name, .plat-swatch-hex, .plat-swatch-cmyk, .plat-chip-flag", eg: ["Jungle #30ba78","CMYK-locked","SPOT","transparent"], live: "swatchCard" },
    { name: "Palette wheel (read-only + editable)", defined: "shells/web/src/lib/palette-wheel.ts:75 / :157", description: "Brand colours on an OKLCH disc (hue=angle, chroma=radius), greys on a lightness rail. Read-only renderPaletteWheel vs editable renderBrandWheel differ only by a --edit modifier + data attrs.", kind: "pure-html-fn", css: ".dash-wheel, .dash-wheel-dot, .dash-wheel-rail, .dash-wheel-preview, .is-editable, .dash-wheel-dot--edit", eg: ["read-only dial","editable brand wheel","greys on rail"], live: "wheel" },
    { name: "Palette preview scenes (poster / chart / UI)", defined: "shells/web/src/lib/palette-preview.ts:212", description: "Three deterministic illustrative SVG mockups painting the palette onto real-looking artwork.", kind: "pure-html-fn", css: "(raw <svg> strings)", eg: ["Poster","Chart","UI card"], live: "palettePreview" },
    { name: "Locked-brand seal", defined: "shells/web/src/lib/brand-seal.ts:87", description: "Turned-metal SVG disc with a padlock, struck in the brand's own inks, when the catalogue brand can't be edited.", kind: "pure-html-fn", css: ".brand-seal, .brand-seal-metal, .brand-seal-lock", eg: ["SUSE slate+jungle","red","neutral fallback"], live: "seal" },
    { name: "Print-lock control (unified)", defined: "shells/web/src/lib/brand-editor.ts:295", description: "Auto/Locked CMYK block + None/Set spot block. RECENTLY UNIFIED from two implementations into mountPrintLock — the model for other unifications.", kind: "needs-host", css: ".be-lock, .be-lock-block, .be-cmyk-inputs, .be-cmyk-in, .be-lock-spot", eg: ["CMYK auto","locked","spot PANTONE 186 C"], code: "printLockHtml() then mountPrintLock(mount, ctx) — ctx supplies hex()/get+setCmyk()/get+setSpot()" },
  ] },
  { group: "common", title: "Navigation, chrome & media", items: [
    { name: "View topbar (gallery/catalog)", defined: "shells/web/src/views/gallery.ts:472", description: "Sticky bar: view-toggle + round FAB cluster (filter/view-opts, history w/ count, language) + profile pill. Near-identical between gallery.ts and catalog.ts, hand-duplicated (rec 11).", kind: "needs-host", css: ".gallery-topbar, .view-toggle-wrap, .gallery-topright, .filter-fab, .history-fab, .cat-viewopts-btn", eg: ["gallery variant","catalog variant","history count badge"], markup: `<div class="gallery-topbar"><div class="view-toggle-wrap"></div><div class="gallery-topright"><button class="filter-fab">⚙</button><button class="history-fab">🕘<span class="history-fab-count">3</span></button><a class="profile-link"></a></div></div>` },
    { name: "Footer nav bar + search box", defined: "shells/web/src/components/footer-nav.ts:40 / :20", description: "Shared fixed bottom bar (Pro/Dashboard/Verify/What? links + a search field) and the icon-prefixed search box. Correctly shared across gallery/projects/catalogue.", kind: "pure-html-fn", css: ".gallery-footer, .gallery-nav-link, .gallery-search-wrap, .gallery-search-box, .gallery-search", eg: ["with Pro link","projects-footer variant"], live: "footerNav" },
    { name: "Featured row / cover-flow carousel", defined: "shells/web/src/components/featured-row.ts:174", description: "Auto-drifting strip of tool tiles cross-fading rendered example looks; toggles to Cover-Flow. Correctly shared across gallery/catalog/projects — the reuse model to follow.", kind: "needs-host", css: ".featured, .featured--coverflow, .featured-track, .ftile, .ftile-stage, .ftile-badge, .ftile-iconfill", eg: ["gallery drift","coverflow","New badge","⋯ menu"], code: "import { mountFeaturedRow } from '../components/featured-row.ts'; mountFeaturedRow(mountEl, entries, host, { viewMode:'gallery', label:'Featured' })" },
    { name: "Icon-backdrop tracer (.gtile-iconfill = .ftile-iconfill)", defined: "shells/web/src/views/gallery.ts:219", description: "Fallback art: the tool's icon as a muted base + an animated green trace behind loading previews. Identical concept under two prefixes.", kind: "markup-only", css: ".gtile-iconfill, .gtile-iconfill-base, .gtile-iconfill-trace, .ftile-iconfill", eg: ["loading trace","settled base"], markup: `<span class="gtile-iconfill"><span class="gtile-iconfill-base"><svg></svg></span><span class="gtile-iconfill-trace"><svg></svg></span></span>` },
    { name: "Category glyph", defined: "shells/web/src/lib/category-icons.ts:67", description: "One inline Lucide SVG per library category, 18px currentColor, grid fallback. One of 3+ icon maps to unify (rec 5).", kind: "pure-html-fn", css: "(inline <svg>)", eg: ["logos","photos","swatches","fonts"], live: "catGlyph" },
    { name: "Upload dropzone", defined: "shells/web/src/lib/upload-dropzone.ts:46", description: "Drag-or-click file ingest area over a hidden input; drives the shared storeUserUpload path.", kind: "needs-host", css: ".updz, .updz--compact, .updz-icon, .updz-copy, .updz-browse, .is-dragover, .is-busy", eg: ["idle","dragover","busy 'Adding 3 files…'","compact"], code: "import { mountUploadDropzone } from '../lib/upload-dropzone.ts'; mountUploadDropzone(el, pickerHost, { compact:true, onAdded:n=>{} })" },
    { name: "Confetti burst", defined: "shells/web/src/lib/particles.ts:178", description: "One-shot full-viewport confetti of labelled chips with drag+gravity on a transient canvas; brand-derived colours. Clone of the /info hero burst (docs/build.ts).", kind: "wired-fn", css: "(inline-styled fixed <canvas>)", eg: ["52-72 chips","brand pairs","reduced-motion skipped"], code: "import { celebrateBurst } from '../lib/particles.ts'; celebrateBurst(window.innerWidth/2, window.innerHeight/2)" },
  ] },
  { group: "view", title: "Gallery", items: [
    { name: "Tool card (masonry tile)", defined: "shells/web/src/views/gallery.ts:1467", description: "Core card: preview visual + caption (icon, name link, desc, last-opened) + action row.", kind: "markup-only", css: ".gtile, .gtile--has-preview, .gtile--unavailable, .gtile-cap, .gtile-name, .gtile-desc, .gtile-actions", eg: ["resumable w","hero","demo preview","icon-led"], markup: `<article class="gtile gtile--has-preview"><div class="gtile-body gtile-body--link"><div class="gtile-cap"><span class="tool-card-icon"></span><span class="gtile-meta"><a class="gtile-name">QR Code</a><p class="gtile-desc">Scannable codes</p></span></div></div><div class="gtile-actions"></div></article>` },
    { name: "Card hero preview + example carousel", defined: "shells/web/src/views/gallery.ts:1593 / :1570", description: "Resume/demo visual with cross-fading frames + time stamp; and the fixed-square scrollable example strip with chevrons/dots.", kind: "markup-only", css: ".gtile-hero, .gtile-hero-frame, .gtile-stamp, .gcar, .gcar-track, .gcar-slide, .gcar-nav, .gcar-dots", eg: ["single session","multi rotate","example dots","deck"], markup: `<button class="gtile-hero gtile-hero--rotate"><img class="gtile-hero-img gtile-hero-frame is-active" src="…"><span class="gtile-stamp">2h ago</span></button>` },
    { name: "Card icon-action buttons + status/New badges", defined: "shells/web/src/views/gallery.ts:1674 / :1481", description: "Round fav/info/history icon buttons (.gtile-iconbtn) and status/New pills.", kind: "markup-only", css: ".gtile-iconbtn, .gtile-fav, .is-fav, .badge, .badge-experimental, .gtile-newbadge", eg: ["star active","info","Experimental","New"], markup: `<div class="gtile-actions"><button class="gtile-iconbtn gtile-fav is-fav" aria-pressed="true"><svg>★</svg></button><button class="gtile-iconbtn"><svg>i</svg></button></div>` },
    { name: "Meta / history dialog + saved-session row", defined: "shells/web/src/views/gallery.ts:1714 / :1903", description: "Native <dialog> info/history shell; and the .saved-row list row (one of THREE saved-session-row systems — rec 6).", kind: "markup-only", css: ".tool-meta-dialog, .meta-dialog-facts, .saved-row, .saved-row--batch, .saved-thumb, .saved-resume, .saved-delete", eg: ["info facts","history session list","batch row"], markup: `<li class="saved-row"><button class="saved-resume"></button><img class="saved-thumb" src="…"><span class="saved-label"><h4>Poster</h4><small>3 Jul 14:20</small></span><button class="saved-delete">✕</button></li>` },
    { name: "Empty / no-results states", defined: "shells/web/src/views/gallery.ts:1090", description: "Status messages for empty grids: no-search-results w/ clear link, no-favourites, load-failed w/ Retry.", kind: "markup-only", css: ".gallery-empty, .gallery-no-results, .gallery-retry, .cat-empty, .cat-retry", eg: ["no match + clear","empty favourites","Retry"], markup: `<p class="gallery-no-results">No tools match "<strong>foo</strong>" — <button class="gallery-retry" data-search-clear>clear search</button></p>` },
  ] },
  { group: "view", title: "Catalog", items: [
    { name: "Asset tile + polymorphic thumbnail", defined: "shells/web/src/views/catalog.ts:807 / :726", description: "Asset card (thumb + caption + source chip + fav star + upload checkbox); thumbnail handles img/video/lottie/audio/stub. NOTE .cat-tile collides with catalog-summary's stat tile.", kind: "markup-only", css: ".cat-tile, .cat-check, .cat-tile-cap, .cat-src, .cat-star, .cat-thumb, .cat-thumb-motion, .cat-thumb-audio", eg: ["asset","user upload w","checkbox","lottie"], markup: `<div class="cat-tile is-fav"><button class="cat-check"></button><button class="cat-tile-open"><span class="cat-tile-fig"><img class="cat-thumb"></span><span class="cat-tile-cap"><span class="cat-tile-name">Logo</span><span class="cat-tile-sub"><span class="cat-src cat-src--user">Yours</span> · PNG</span></span></button><button class="cat-star">★</button></div>` },
    { name: "Collapsible group + sticky toolbar", defined: "shells/web/src/views/catalog.ts:708 / :1028", description: "Folding section shell (header button, chevron, glyph, title, count pill) and the floating filetype-filter toolbar. NOTE .cat-group* classes reused by catalog-summary with divergent markup.", kind: "markup-only", css: ".cat-group, .is-collapsed, .cat-group-head, .cat-group-chevron, .cat-group-count, .cat-toolbar, .cat-typefilter, .cat-count", eg: ["expanded","collapsed","All filter","Motion selected"], markup: `<section class="cat-group"><button class="cat-group-head" aria-expanded="true"><span class="cat-group-chevron">▸</span><span class="cat-group-icon">▦</span><span class="cat-group-title">Logos</span><span class="cat-group-count">12</span></button><div class="cat-group-body"><div class="cat-grid"></div></div></section>` },
    { name: "Bulk-action bar + colour/treatment swatch row", defined: "shells/web/src/views/catalog.ts:1187 / :786", description: "Multi-select bar (count + Duplicate/Download/Delete + clear) and the duo-colour swatch/treatment row (overloaded across pickers/treatments/headers/download; had a [data-theme] collision bug).", kind: "markup-only", css: ".cat-bulkbar, .cat-bulk-danger, .cat-dl-themes, .cat-dl-theme, .cat-dl-duo, .cat-dl-treat", eg: ["3 selected","icon colour duos","photo treatments"], markup: `<div class="cat-bulkbar"><span class="cat-bulkbar-count">3 selected</span><div class="cat-bulkbar-actions"><button class="btn cat-bulk-danger" data-bulk="delete">Delete</button></div><button class="cat-bulkbar-clear">✕</button></div>` },
    { name: "Asset details / download / crop dialogs", defined: "shells/web/src/views/catalog.ts:1360 / :2424", description: "Full-screen asset dialog (zoom HUD, meta dl, credential panel, actions) and the download/crop dialogs. Own zoom HUD (.cat-zoom-hud — rec 8) and own <dialog> lifecycle (rec 4).", kind: "needs-host", css: ".cat-details, .cat-zoom-hud, .cat-zoom-btn, .cat-details-actions, .cat-dl, .cat-dl-fmt, .cat-crop, .cat-crop-box", eg: ["zoomable image + HUD","credential panel","SVG download","crop box"], markup: `<dialog class="cat-details"><button class="cat-details-close">×</button><div class="cat-details-preview is-zoomable"><div class="cat-zoom-stage"><img class="cat-thumb"></div><div class="cat-zoom-hud"><button class="cat-zoom-btn" data-zoom="out">−</button><button class="cat-zoom-btn cat-zoom-pct">100%</button><button class="cat-zoom-btn" data-zoom="in">+</button></div></div></dialog>` },
    { name: "Font specimen card + reference download", defined: "shells/web/src/views/catalog.ts:1149 / :1138", description: "Per-font card (Aa specimen, pangram, weight ramp, type dl) and the pill download button for palette/font exports.", kind: "markup-only", css: ".plat-font, .cat-font, .plat-font-specimen, .plat-font-aa, .plat-font-weights, .cat-download, .cat-font-downloads", eg: ["heading font","body font","tokens JSON download"], markup: `<article class="plat-font cat-font"><header class="plat-font-head"><span class="plat-font-name">Poppins</span><span class="plat-font-role">Heading</span></header><div class="plat-font-specimen"><div class="plat-font-aa">Aa</div><p class="plat-font-pangram">The quick brown fox…</p></div></article>` },
  ] },
  { group: "view", title: "Dashboard & Brand studio", items: [
    { name: "Brand hero", defined: "shells/web/src/views/dashboard.ts:159", description: "Read-only card wearing the brand's --brand-* slots: logo, name, status, #/start CTA, click-to-copy primary chip.", kind: "needs-host", css: ".dash-hero, .dash-hero-name, .dash-hero-status, .dash-hero-cta, .dash-hero-primary", eg: ["unbranded","installed brand","locked (seal)"], markup: `<section class="plat-section dash-section dash-hero"><div class="dash-hero-main"><div class="dash-hero-id"><span class="dash-hero-eyebrow">The brand in force</span><h2 class="dash-hero-name">SUSE</h2></div><button class="dash-hero-primary"><span class="dash-hero-primary-label">Primary</span><code class="dash-hero-primary-code">#30BA78 · oklch(…)</code></button></div></section>` },
    { name: "Ink ribbon + shared readout", defined: "shells/web/src/views/dashboard.ts:291", description: "Every palette colour as a thin bar grouped by family; hover drives one shared mono readout. One of three readout instruments.", kind: "markup-only", css: ".dash-ribbon, .dash-ink, .is-measured, .dash-ink-group, .dash-readout, .dash-readout-swatch, .dash-readout-hex", eg: ["brand row","spectrum group","measured tick"], markup: `<div class="dash-ribbon"><div class="dash-ink-group"><span class="dash-ink-group-label">Brand</span><div class="dash-ink-row"><button class="dash-ink is-measured" style="--ink:#30ba78"></button></div></div></div><div class="dash-readout"><span class="dash-readout-swatch"></span><span class="dash-readout-name">Jungle</span><code class="dash-readout-hex">#30BA78</code></div>` },
    { name: "Type-in-motion demo + type facts", defined: "shells/web/src/lib/type-demo.ts:161 / views/dashboard.ts:470", description: "Live variable-font showcase (faux terminal + breathing display word, editable) and the faces-in-force facts strip.", kind: "wired-fn", css: ".type-demo, .td-half, .td-term, .td-sample, .td-range, .dash-type-facts, .dash-type-fam", eg: ["two-up","single face","empty"], code: "import { renderTypeDemo, wireTypeDemo } from '../lib/type-demo.ts'; const html = renderTypeDemo(); wireTypeDemo(rootEl)" },
    { name: "Capability card + detail modal + storage donut", defined: "shells/web/src/views/dashboard.ts:386 / :568", description: "Card-button popping a feature list into a shared <dialog>, and the SVG storage ring + composition bar.", kind: "markup-only", css: ".dash-cap-card, .dash-cap-peek, .dash-cap-modal, .dash-store-donut, .dash-donut-arc, .dash-store-bar, .dash-store-seg", eg: ["card w","peek + count","storage 12% ring"], markup: `<div class="dash-cap-item"><button class="dash-cap-card" data-cap-open><span class="dash-cap-icon">◆</span><span class="dash-cap-title">Make</span><ul class="dash-cap-peek"><li>Vector</li></ul><span class="dash-cap-foot"><span class="dash-cap-n">2</span></span></button></div>` },
    { name: "Editable palette wheel + swatch tiles + editor popover", defined: "shells/web/src/lib/palette-wheel.ts:157 / brand-editor.ts:437 / :793", description: "Live drag-to-recolour wheel, editable .be-swatch tiles grouped with +Add, and the anchored swatch editor popover. Swatch tiles are one of 4 renderings of PaletteEntry (rec 12).", kind: "pure-html-fn", css: ".dash-wheel.is-editable, .be-swatch, .be-swatch.is-empty, .be-pal-group, .be-editor, .be-editor-card", eg: ["draggable dots","filled+empty tiles","editor popover"], code: "import { renderBrandWheel } from '../lib/palette-wheel.ts'; renderBrandWheel([{idx:0,hex:'#30ba78',label:'Primary'},{idx:1,hex:'#0c322c',label:'Jungle'}]) // wireBrandWheel(root, handlers)" },
    { name: "Derive preview: ramps + specimen cards", defined: "shells/web/src/lib/brand-editor.ts:167", description: "9-step ramp rows (steps selectable) + Light/Dark specimen cards with WCAG/APCA ratios.", kind: "markup-only", css: ".be-ramps, .be-ramp-row, .be-ramp-cell, .is-selected, .be-specs, .be-spec, .be-spec-ratio", eg: ["Primary ramp","Neutral ramp w","selected step","Light+Dark specimen"], markup: `<div class="be-ramp-row"><span class="be-ramp-label">Neutral</span><div class="be-ramp"><button class="be-ramp-cell" style="background:#eee"></button><button class="be-ramp-cell is-selected" style="background:#999"></button></div></div>` },
    { name: "Start step tabs + import drop card + mobile sheet", defined: "shells/web/src/views/start.ts:110 / :127 / :665", description: "Numbered step tablist (third tablist system), the import format-tile dropzone, and the mobile palette bottom sheet (.stu-chip = 4th swatch rendering).", kind: "markup-only", css: ".start-tabs, .start-tab, .is-nudge, .start-import-drop, .start-import-fmt, .stu-sheet, .stu-chip", eg: ["active step 2","dragover","peek strip"], markup: `<nav class="start-tabs" role="tablist"><button class="start-tab is-active" role="tab"><span class="start-tab-n">1</span><span class="start-tab-label">Logos</span></button><button class="start-tab is-nudge" role="tab"><span class="start-tab-n">2</span><span class="start-tab-label">Colours</span></button></nav>` },
  ] },
  { group: "view", title: "Tool sidebar & inputs", items: [
    { name: "Collapsible input section + searchable select + asset picker", defined: "shells/web/src/views/tool-inputs.ts:345 / :1259 / :1307", description: "<details> input group, filterable select (>10 opts), and the asset-picker row (thumb + trigger + clear, brand-tinted for live Lolly renders) with a provenance sub-row.", kind: "markup-only", css: ".input-section, .select-search, .asset-picker-row, .asset-picker-trigger, .is-lolly, .asset-from-tool, .asset-from-tool--baked", eg: ["open section","filterable select","lottie thumb","✦ from QR Code"], markup: `<div class="asset-picker-row is-lolly"><img class="asset-picker-thumb-inline" src="…"><button class="asset-picker-trigger"><span class="asset-lolly-spark">✦</span> Logo</button><button class="asset-clear">✕</button></div>` },
    { name: "Blocks input + block item card", defined: "shells/web/src/views/tool-inputs.ts:1624 / :1575", description: "Repeating field-group editor (cards/typed/tree/droppable) with draggable block cards that fold to a pill.", kind: "markup-only", css: ".blocks-input, .blocks-list, .blocks-toolbar, .block-item, .is-collapsed, .block-head, .block-fields, .block-grip", eg: ["flat cards","typed add-menu","tree","collapsed pill"], markup: `<div class="blocks-input blocks-input--cards"><div class="blocks-list"><div class="block-item is-typed"><div class="block-head" draggable="true"><svg class="block-grip"></svg><span class="block-type-label">Text</span><span class="block-head-preview">Hello</span></div><div class="block-fields"></div></div></div><button class="block-add">+ Add</button></div>` },
    { name: "Block field controls + reference picker + asset field", defined: "shells/web/src/views/tool-inputs.ts:1369 / :1379 / :1473", description: "Per-field controls inside a block (text/select/number/range/checkbox/color/asset), the ref combobox pointing at another blocks input, and the per-block image trigger.", kind: "markup-only", css: ".block-control, .block-field, .block-field--ref, .block-asset, .block-asset-trigger, .block-asset-edit", eg: ["labelled text","range","ref select","block image"], markup: `<div class="block-control"><span class="block-control-label">Heading</span><input class="block-field block-field--full" data-field-id="scenes:0:heading" value="Intro"></div>` },
    { name: "Embed editor overlay", defined: "shells/web/src/views/tool-inputs.ts:1716", description: "Modal re-opening a Lolly-sourced image's source tool inputs (throwaway child runtime) with a live preview + format/size controls.", kind: "needs-host", css: ".embed-editor-overlay, .embed-editor-panel, .embed-editor-head, .ee-inputs, .ee-preview, .ee-apply", eg: ["Edit mode","Insert mode","Rendering…"], code: "await openEmbedEditor(host, { editUrl:'https://lolly.tools/#/t/qr-code?url=…', slotLabel:'Logo', mode:'edit' })" },
  ] },
  { group: "view", title: "Export panel", items: [
    { name: "Export disclosure cards (CMYK / password / C2PA / print)", defined: "shells/web/src/views/tool-actions.ts:297", description: "FOUR format-gated cards sharing an identical icon-head + body + hint anatomy but with entirely bespoke class names. Prime target for a shared .section-card base (rec 7).", kind: "markup-only", css: ".export-cmyk, .export-pdfpass, .export-c2pa, .export-print, .cmyk-hint, .pdfpass-tier, .c2pa-life, .print-toggles", eg: ["CMYK profile","Password (collapsed","open)","C2PA + lifetime"], markup: `<div class="export-print"><label class="print-enable"><input type="checkbox" data-action="print-enable"><span class="print-head">Print marks &amp; bleed</span></label><div class="print-body"></div></div>` },
    { name: "Filename+format row + dimensions row", defined: "shells/web/src/views/tool-actions.ts:240 / :255", description: "CSS-fused filename+format select and the W/H number fields + unit select + DPI-for-physical-units.", kind: "markup-only", css: ".filename-extension, .export-filename, .export-dims, .dim-field, .dim-icon, .dim-unit, .dim-dpi", eg: ["name + PNG","210×297 mm w","DPI"], markup: `<div class="export-dims"><div class="dim-field"><svg class="dim-icon"></svg><input type="number" data-action="export-width" data-scrub value="800"></div><select class="dim-unit"><option>px</option><option>mm</option></select></div>` },
    { name: "Export action buttons + render pill + popup overlay", defined: "shells/web/src/views/tool-actions.ts:507 / tool.ts:760 / :772", description: "Copy/Save/Share + Download row (button-name fragmentation: .save-btn vs .render-pill-save), the floating Get|Save render pill, and the export popup modal.", kind: "markup-only", css: ".export-action-buttons, .copy-btn, .save-btn, .copy-url-btn, .render-pill, .render-pill-save, .export-overlay, .export-popup", eg: ["Copy","Save","Share","Export"], markup: `<div class="render-pill" role="group"><button class="render-pill-btn render-pill-get"><svg class="render-pill-icon">↑</svg><span>Export</span></button><span class="render-pill-sep"></span><button class="render-pill-btn render-pill-save"><span data-save-label>Save</span></button></div>` },
    { name: "Audio track card + video params", defined: "shells/web/src/views/tool-actions.ts:472 / :439", description: "Music-bed picker (optgroup select + preview + fade/duck) and the wait/duration + dither/60fps cluster for animated formats.", kind: "markup-only", css: ".export-audio, .audio-pick, .audio-preview, .is-playing, .video-params, .vp-field, .gif-dither-toggle", eg: ["track selected","previewing","Wait 1s Duration 5s"], markup: `<div class="export-audio"><span class="audio-head">Audio track</span><div class="audio-pick"><select data-action="video-audio"><option>None</option></select><button class="audio-preview">▶</button></div></div>` },
    { name: "Stage zoom HUD", defined: "shells/web/src/views/tool-stage-nav.ts:257", description: "Floating −/percent/+/Fit control on the canvas, optionally with theme+sound toggles. One of three zoom HUDs (rec 8).", kind: "needs-host", css: ".stage-nav, .stage-nav-btn, .stage-nav-pct, .stage-nav-fit, .stage-nav-sep", eg: ["100% Fit","150% zoomed","with toggles"], code: "setupStageNav(stageEl, outerEl, canvasEl, 800, onFit, themeToggle, soundToggle)" },
  ] },
  { group: "view", title: "Pro / batch", items: [
    { name: "Pro batch toolbar", defined: "shells/web/src/pro/index.ts:185", description: "Top control bar: hamburger, zip-name field, interface zoom, unit/DPI/format selectors, Sessions + Render buttons. Own button family (.pro-btn) and zoom (rec 2, 8).", kind: "markup-only", css: ".pro-toolbar, .pro-hamburger, .pro-btn, .pro-btn--primary, .pro-format, .pro-zip, .pro-zoom", eg: ["full desktop bar","collapsed","Render primary"], markup: `<div class="pro-toolbar"><button class="pro-btn pro-hamburger">☰</button><label class="pro-format pro-zip"><span class="pro-zip-ext">.zip</span></label><button class="pro-btn pro-btn--primary">Render</button></div>` },
    { name: "Pro grid + cell controls", defined: "shells/web/src/pro/grid.ts:374 / controls.ts:52", description: "The spreadsheet (sticky merged input columns + fixed output columns) and the minimal per-type control factory — the batch counterpart to sidebar controlHtml (second control factory, rec: inputs).", kind: "pure-html-fn", css: ".pro-grid, .pro-col, .pro-col-fixed, .pro-cell, .pro-control, .pro-num, .pro-vec-field, .pro-asset-thumb", eg: ["empty hint","rows w","merged columns","select cell"], live: "proControl" },
    { name: "Pro column header + template cell", defined: "shells/web/src/pro/grid.ts:121 / :286", description: "Column label with a fill-down bucket + ≠ mismatch flag, and the per-row template picker with format select + preview eye.", kind: "markup-only", css: ".pro-col-head, .pro-fill-btn, .pro-col-flag, .pro-cell-template, .pro-template-trigger, .pro-fmt, .pro-eye", eg: ["fillable column","picked tool + PNG","experimental"], markup: `<th class="pro-col"><div class="pro-col-head"><button class="pro-col-label" data-collapse-col="headline">Headline</button><button class="pro-fill-btn" data-bulk-col="headline">🪣</button></div></th>` },
    { name: "Pro popover (template search / bulk-fill / sessions)", defined: "shells/web/src/pro/index.ts:533", description: "Anchored popover shared across combobox template search, bulk column-fill, and the batch sessions/CSV manager.", kind: "needs-host", css: ".pro-popover, .pro-tpl-popover, .pro-tpl-list, .pro-popover-actions, .pro-popover--sessions, .pro-sess-list", eg: ["template search","Fill 'Headline' 5 rows","sessions + CSV"], markup: `<div class="pro-popover"><div class="pro-popover-title">Fill "Headline" · 5 rows</div><div class="pro-popover-control"></div><div class="pro-popover-actions"><button class="pro-btn pro-btn--primary">Apply to 5</button></div></div>` },
  ] },
  { group: "view", title: "Multi-edit", items: [
    { name: "Multi-edit header + canvas cell", defined: "shells/web/src/views/multi-edit.ts:219 / :175", description: "Top bar (back, title+count, Save-all/Download-all using bare .btn) and the clickable scaled-canvas cell.", kind: "markup-only", css: ".me-head, .me-title, .me-count, .me-primary, .me-cell, .me-stage, .me-canvas, .me-cap, .is-active", eg: ["'4 designs'","active cell","flash"], markup: `<figure class="me-cell" role="button"><div class="me-stage" style="aspect-ratio:800/600"><div class="me-scale"><div class="me-canvas"></div></div></div><figcaption class="me-cap"><span class="me-cap-label">Poster A</span><span class="me-cap-tool">Brand Lockup</span></figcaption></figure>` },
    { name: "Multi-edit combined sidebar + zoom bar + condensed export", defined: "shells/web/src/views/multi-edit.ts:233 / :245 / :193", description: "Search + Shared fan-out card + per-session <details> cards (reuse renderInputs), the N-across zoom bar (rec 8), and the compact per-card export block.", kind: "markup-only", css: ".me-sidebar, .me-card, .me-card--shared, .me-inputs, .me-zoom, .me-zoom-read, .me-export, .me-exp-field", eg: ["Shared 3 inputs","per-session card","3 across","PNG export"], markup: `<details class="me-card me-card--shared" open><summary><span class="me-card-title">Shared</span><span class="me-card-count">3 inputs · applies to every design</span></summary><div class="tool-inputs me-inputs"></div></details>` },
  ] },
  { group: "view", title: "Projects / folders", items: [
    { name: "Session / folder / user-image tiles", defined: "shells/web/src/folder-tiles.ts:142 / :221 / :190", description: "The shared grid tiles: saved-session (thumb/batch cover), folder (2×2 mosaic), user-image. sessionTile is one of THREE saved-session-row systems (rec 6); owns the canonical badges + fmtBytes.", kind: "pure-html-fn", css: ".folder-tile, .tile-cover, .tile-cover--batch, .tile-badges, .tile-menu-btn, .folder-tile--folder, .folder-mosaic", eg: ["session w","thumb","batch package","folder mosaic"], code: "import { sessionTile, folderTile } from '../folder-tiles.ts'; sessionTile({ slot:'qr-code:171', toolId:'qr-code', label:'Launch QR', thumb:null, updatedAt:'2026-07-09T10:00:00Z' }, { toolName:'QR Code', sizeBytes:20480, tool:{ formats:['svg'], width:512, height:512, unit:'px', exportable:true } })" },
    { name: "Folder / context menu + header + Move-to rail", defined: "shells/web/src/views/projects.ts:1013 / :460 / :419", description: "Icon+label action menu (TWO implementations — projects vs folder-overlay, rec 9), the breadcrumb header, and the drop-target folder-chip rail.", kind: "markup-only", css: ".folder-menu, .projects-menu, .folder-menu-item--danger, .projects-head, .projects-crumbs, .projects-rail, .projects-chip, .is-drop", eg: ["folder actions","nested breadcrumb","drop rail"], markup: `<div class="folder-menu projects-menu"><button class="folder-menu-item" data-act="open">Open</button><button class="folder-menu-item folder-menu-item--render" data-act="render">Render</button><button class="folder-menu-item folder-menu-item--danger" data-act="delete">Delete</button></div>` },
    { name: "Bulk bar + tool picker + search", defined: "shells/web/src/views/projects.ts:637 / :1368 / :613", description: "Floating selection bar, the modal tool chooser grid (shares pattern with move-picker + name-prompt), and the scope-aware search box + no-results.", kind: "markup-only", css: ".projects-bulkbar, .projects-bulk-danger, .toolpicker-grid, .toolpicker-tile, .toolpicker-add, .projects-search-box, .projects-empty", eg: ["3 selected","tool grid","'12 results'"], markup: `<div class="toolpicker-cell"><button class="toolpicker-tile"><span class="toolpicker-icon">▣</span><span class="toolpicker-name">QR Code</span></button><button class="toolpicker-add"><span class="toolpicker-add-label">+ Add</span></button></div>` },
    { name: "Folder overlay dialog", defined: "shells/web/src/folder-overlay.ts:81", description: "File-manager modal over saved sessions/images: folder grid + loose grid, nav, create/rename/delete, per-item move menu, batch export. Shared across gallery/pro/picker/projects.", kind: "needs-host", css: ".folder-overlay, .folder-overlay-head, .folder-grid, .folder-newbtn, .folder-exportbtn, .folder-ask, .folder-ask-card", eg: ["root","inside folder","empty","name-ask"], code: "import { openFolderOverlay } from './folder-overlay.ts'; openFolderOverlay(host, { context:'projects', sessionEntries, imageRefs, sessionSizes, nameById, showCreateFolder:true, allowBatchExport:true, onResume(){} })" },
  ] },
  { group: "view", title: "Profile", items: [
    { name: "Details card + field + appearance theme cards", defined: "shells/web/src/views/profile.ts:223 / :270", description: "Base .profile-card + floating-label fields + opt-in pill, and the clickable theme-preview swatch cards (token dots + Aa). Theme cards are one of ~4 theme UIs (rec 12).", kind: "markup-only", css: ".profile-card, .profile-field, .profile-check, .profile-theme, .profile-theme-dots, .profile-theme-sample, .is-active", eg: ["field grid","light (default pill, active)","dark"], markup: `<button class="profile-theme is-active" data-theme="light" aria-pressed="true"><div class="profile-theme-name">Light<span class="profile-theme-pill">default</span></div><div class="profile-theme-dots"><span></span><span></span><span></span><span></span><span></span></div><div class="profile-theme-sample">Aa</div></button>` },
    { name: "Collapsible section + feature-flag rows", defined: "shells/web/src/views/profile.ts:286 / :202", description: "<details> card whose summary is an h2 + chevron (own .profile-collapse, rec 7), and the feature-flag switch list with (i) info popovers.", kind: "markup-only", css: ".profile-collapse, .profile-collapse-summary, .profile-collapse-chev, .feature-flags, .feature-flag-switch, .feature-flag-info-pop", eg: ["collapsed","open","flag on w","Beta pill"], markup: `<details class="profile-card profile-collapse" open><summary class="profile-collapse-summary"><h2>Storage</h2><svg class="profile-collapse-chev"></svg></summary><div class="profile-collapse-body"></div></details>` },
    { name: "Storage meter + session row", defined: "shells/web/src/views/profile.ts:617 / :589", description: "Device-storage hero (animated total, segmented bar, legend, quota, manage panels) and the .store-sess session row (THIRD saved-session-row system, rec 6).", kind: "needs-host", css: ".store-meter, .store-hero-num, .store-bar, .seg, .store-legend, .store-chip, .store-sess, .store-sess-thumb, .store-sess-del", eg: ["hero '124 MB'","4-segment bar","session row w","delete"], markup: `<li class="store-sess"><input type="checkbox" class="store-sess-check"><img class="store-sess-thumb"><span class="store-sess-meta"><span class="store-sess-label">Launch QR<span class="store-sess-tag">batch</span></span><span class="store-sess-sub">QR Code · 2d ago</span></span><span class="session-size">20 KB</span><button class="store-sess-del">✕</button></li>` },
    { name: "Confirm / type-a-word gate dialogs", defined: "shells/web/src/views/profile.ts:1043", description: "Body-level overlay (NOT native <dialog>) with a randomised type-to-confirm word gate; re-traps focus by hand ~4× (clear/hoard/import/keep-active). Rec 4 target.", kind: "markup-only", css: ".clear-dialog-overlay, .clear-dialog, .clear-confirm-input, .clear-dialog-actions, .btn-danger, .info-dot, .info-tip", eg: ["clear-data (danger)","hoard 'Type vault'","import"], markup: `<div class="clear-dialog-overlay"><div class="clear-dialog" role="dialog"><h3>Clear all my data?</h3><label class="clear-confirm"><span class="clear-confirm-prompt">Type <strong>privacy</strong> to confirm</span><input class="clear-confirm-input"></label><div class="clear-dialog-actions"><button class="btn btn-danger" disabled>Clear everything</button><button class="btn">Cancel</button></div></div></div>` },
    { name: "Content-credentials card + user-image lightbox", defined: "shells/web/src/views/profile.ts:1361 / :1509", description: "Enrolled status card or enroll form (provider buttons, lifetime select), and the user-image grid + full-size lightbox.", kind: "needs-host", css: ".identity-status, .identity-signing, .identity-providers, .userimg-grid, .userimg-item, .userimg-lightbox-overlay", eg: ["enroll form","signing-as","expired","lightbox"], code: "renderIdentityStatus(s) / renderEnrollForm(caHealth) — module-private, driven by host.identity.status()" },
    { name: "Profile mobile menu popover", defined: "shells/web/src/components/profile-menu.ts:86", description: "Right-aligned avatar popover: theme radio-segment group, Saved-sessions (count), brand + settings links; focus-trapped. Duplicates lang-menu popover lifecycle (rec 9).", kind: "needs-host", css: ".profile-menu, .profile-menu-theme, .profile-menu-seg, .profile-menu-item, .profile-menu-count", eg: ["3 theme segments","Saved ×7","brand+settings"], code: "import { attachProfileMenu } from '../components/profile-menu.ts'; attachProfileMenu(triggerEl, host, { savedCount:7, onHistory(){} })" },
  ] },
  { group: "view", title: "Verify (/valid)", items: [
    { name: "Hero result + verdict states + scorecard pips", defined: "shells/web/src/views/valid.ts:830 / :270", description: "The /valid headline with 9 state classes tinting everything, plus the 8 canonical C2PA check pips (full + mini). Mostly module-private (rec: export or fixture to gallery).", kind: "markup-only", css: ".valid-result, .is-lolly, .is-trusted, .is-invalid, .valid-hero-pill, .valid-score, .valid-score-pip, .is-pass, .is-fail, .is-warn", eg: ["Made with Lolly (green)","Verified (trusted)","broken (red)","all-pass pips"], code: "resolveState(report) → STATE_COPY; scorecardHtml(report)/miniScoreHtml(report) are module-private" },
    { name: "AI-generated banner + change-history + assertion-log", defined: "shells/web/src/views/valid.ts:529 / :633 / :695", description: "Purple AI alert, the boxed C2PA action timeline (exported stepsHtml), and the raw verifier check list (module-private checksHtml).", kind: "pure-html-fn", css: ".valid-ai-flag, .valid-steps, .valid-panel, .valid-step, .is-lolly, .is-ai, .valid-checks, .valid-check--ok, .valid-check--bad", eg: ["AI-generated","Created (Lolly)","Colour adjusted (Adobe)","ok"], live: "validSteps" },
    { name: "'Made from' inputs panel + facts/summary panel", defined: "shells/web/src/views/valid.ts:301 / :765", description: "Boxed digest of recorded scalar inputs (exported inputsDigestHtml, swatch for hex) and the facts <dl> summary flowing into a 2-col masonry (module-private fact()).", kind: "pure-html-fn", css: ".valid-inputs, .valid-input-row, .valid-input-swatch, .valid-summary, .valid-facts, .valid-fact, .valid-panels", eg: ["Background #1a1a2e (swatch)","Headline 'Ship it'","fact list"], live: "validInputs" },
    { name: "Metadata reveal + media preview + drop zone + batch item", defined: "shells/web/src/views/valid.ts:471 / :720", description: "EXIF/XMP reveal with sensitive marking + clean-copy link + offline SVG GPS locator, and the verify surface chrome (drop zone, media previews, collapsible batch items). Mostly module-private.", kind: "markup-only", css: ".valid-meta, .valid-meta-group, .is-sensitive, .valid-locator, .valid-clean-link, .valid-drop, .valid-preview, .valid-item, .valid-item-badge", eg: ["12 fields","GPS pin","drop idle","over"], code: "mediaPreviewHtml(preview,'lg') + <details class=\"valid-item\"> summaryInner(name, report) are module-private; drop zone is static markup in mountValid()" },
  ] },
];
