// SPDX-License-Identifier: MPL-2.0
/**
 * The browsable component library (#/components).
 *
 * A dev/design surface, off every hot path (lazy-loaded). It renders the shell's
 * components — common primitives first, then per-view — from the audit inventory
 * in components-data.ts (generated by the component-audit workflow; the written
 * analysis is plans/component-audit.md). Each specimen is shown live where the
 * component is a pure render function, as a static markup sample where it's only
 * CSS, and as a labelled source snippet where it needs the host bridge to run.
 *
 * The page has one nav affordance: a back control that returns you where you came
 * from IF you arrived from inside Lolly (cameFromApp → history.back()), else drops
 * you at the gallery. Nothing here mutates app or brand state.
 *
 * Specimens are styled by the real part sheets, imported below so each looks
 * exactly as it does in situ.
 */

import '../styles/parts/components-lib.css';
// The specimens borrow the app's own stylesheets. The globally-@imported parts
// (components, gallery, topbar, catalog, dialogs, featured, folders, projects,
// saved-list — see styles/app.css) are already present; these view-local sheets
// are not on the landing bundle, so pull them in for the samples that need them.
import '../styles/parts/platform.css';
import '../styles/parts/dashboard.css';
import '../styles/parts/brand-studio.css';
import '../styles/parts/tool.css';
import '../styles/parts/tool-chrome.css';
import '../styles/parts/storage.css';
import '../styles/parts/profile.css';
import '../styles/parts/start.css';
import '../styles/parts/multi-edit.css';
import '../styles/parts/valid.css';

import { t } from '../i18n.ts';
import { escape } from '../utils.ts';
import { armViewEnter } from '../view-enter.ts';
import type { HostV1 } from '../../../../engine/src/bridge/host-v1.ts';
import { AUDIT_SECTIONS, type Specimen } from './components-data.ts';

import { colorFieldHtml, wireColorField } from '../components/color-field.ts';
import { renderPaletteWheel, wirePaletteWheel } from '../lib/palette-wheel.ts';
import { renderBrandSeal, sealColors } from '../lib/brand-seal.ts';
import { swatch } from '../lib/swatches.ts';
import { genAiPill } from '../lib/genai-pill.ts';
import { lollyBadge } from '../lib/lolly-badge.ts';
import { viewToggle } from '../components/view-toggle.ts';
import { themeSegmentHtml } from '../components/theme-toggle.ts';
import { soundSwitchHtml } from '../components/sound-toggle.ts';
import { helpTip } from '../components/help-tip.ts';
import { footerNav, gallerySearchBox } from '../components/footer-nav.ts';
import { confirmDialog, choiceDialog, noticeDialog, promptDialog } from '../components/confirm-dialog.ts';
import { openShareDialog } from '../components/share-dialog.ts';
import { palettePreviewSvgs } from '../lib/palette-preview.ts';
import { categoryGlyph } from '../lib/category-icons.ts';
import { catalogSummaryBody } from '../lib/catalog-summary.ts';
import { fmtBadge, dimBadge, rowCountBadge } from '../folder-tiles.ts';
import { controlHtml } from '../pro/controls.ts';
import { stepsHtml, inputsDigestHtml } from './valid.ts';
import type { PaletteEntry } from '../palette.ts';

// A demo palette for the colour specimens (not the live brand).
const DEMO: PaletteEntry[] = [
  { hex: '#30ba78', label: 'Jungle', cmyk: [74, 0, 60, 0], group: 'Brand' },
  { hex: '#0c322c', label: 'Pine', cmyk: [80, 30, 55, 60], group: 'Brand' },
  { hex: '#2453ff', label: 'Klein', cmyk: [86, 68, 0, 0], group: 'Spectrum' },
  { hex: '#fe7c3f', label: 'Persimmon', cmyk: [0, 60, 78, 0], group: 'Spectrum' },
  { hex: '#efefef', label: 'Mist', cmyk: [0, 0, 0, 6], group: 'Neutral' },
  { hex: '#1b1b1b', label: 'Ink', cmyk: [0, 0, 0, 92], group: 'Neutral' },
];

// A live-openable dialog trigger — the honest sample for an imperative component.
function triggerButton(label: string, onClick: () => void): HTMLElement {
  const b = document.createElement('button');
  b.type = 'button'; b.className = 'be-cta'; b.textContent = label;
  b.addEventListener('click', onClick);
  return b;
}

/** The live renderers, keyed by the `live` tag in components-data.ts. Each returns
 *  an HTML string or a node; a `wire` runs after it's inserted. Only pure/wired
 *  components with a safe render path are here — everything else falls back to a
 *  markup sample or a source snippet. */
const LIVE: Record<string, { render: () => string | HTMLElement; wire?: (stage: HTMLElement) => void }> = {
  colorField: { render: () => colorFieldHtml('cl-color', '#30ba78', { inline: true, modes: true }), wire: (s) => wireColorField(s) },
  wheel: { render: () => `<div style="width:320px;max-width:100%">${renderPaletteWheel(DEMO.map(p => ({ hex: p.hex, label: p.label })))}</div>`, wire: (s) => wirePaletteWheel(s) },
  seal: { render: () => renderBrandSeal(sealColors(DEMO), 128) },
  swatchCard: { render: () => `<div style="display:grid;grid-template-columns:1fr 1fr;gap:.6rem;width:100%">${swatch(DEMO[0]!)}${swatch({ ...DEMO[1]!, spot: { name: 'PANTONE 5535 C' } })}</div>` },
  palettePreview: { render: () => `<div style="width:340px;max-width:100%">${palettePreviewSvgs(['#2453ff', '#30ba78', '#fe7c3f', '#e11d48'])[0]?.svg ?? ''}</div>` },
  genai: { render: () => `${genAiPill('full')} ${genAiPill('partial')} ${genAiPill('full', true)}` },
  lollyBadge: { render: () => `${lollyBadge('sm')} ${lollyBadge('lg')}` },
  viewToggle: { render: () => viewToggle('tools') },
  themeSeg: { render: () => themeSegmentHtml() },
  soundSwitch: { render: () => soundSwitchHtml() },
  footerNav: { render: () => footerNav({ proEnabled: false, searchHtml: gallerySearchBox({ placeholder: t('Search'), ariaLabel: t('Search') }) }) },
  catGlyph: { render: () => `<span style="display:inline-flex;gap:.7rem;align-items:center">${['logos', 'photos', 'swatches', 'fonts'].map(categoryGlyph).join('')}</span>` },
  catSummary: { render: () => catalogSummaryBody([
    { id: 'qr-code', category: 'utility', status: 'official' },
    { id: 'brand-lockup', category: 'designer', status: 'experimental' },
    { id: 'street-map', category: 'utility', status: 'official' },
  ] as never) },
  tileBadges: { render: () => `<span class="tile-badges">${fmtBadge('svg')}${dimBadge(512, 512, 'px')}${rowCountBadge(8)}</span>` },
  dialogTriggers: {
    render: () => {
      const wrap = document.createElement('div');
      wrap.style.cssText = 'display:flex;gap:.5rem;flex-wrap:wrap';
      wrap.append(
        triggerButton(t('Confirm…'), () => { void confirmDialog({ title: t('Delete swatch?'), message: t('This can’t be undone.'), confirmLabel: t('Delete') }); }),
        triggerButton(t('Choose…'), () => { void choiceDialog({ title: t('Export as'), message: t('Pick a format'), choices: [{ id: 'png', label: 'PNG' }, { id: 'svg', label: 'SVG' }] as never }); }),
        triggerButton(t('Notice…'), () => { void noticeDialog({ title: t('Heads up'), message: t('A sample notice.') }); }),
        triggerButton(t('Prompt…'), () => { void promptDialog({ title: t('Name this'), message: t('Give it a name'), placeholder: t('e.g. Jungle') }); }),
      );
      return wrap;
    },
  },
  shareTrigger: { render: () => triggerButton(t('Share…'), () => { openShareDialog({ toolId: 'qr-code', baseParts: ['url=https%3A%2F%2Fsuse.com'], currentFormat: 'png', title: t('Share this tool') }); }) },
  helpTip: {
    render: () => { const h = helpTip(t('Chroma is how vivid a colour is — grey at the centre, vivid at the rim.'), { href: '#/components', text: t('Learn more') }); return `<span class="help-tip-host" style="display:inline-flex;align-items:center;gap:.4rem">${t('Chroma')} ${h.button}${h.pop}</span>`; },
  },
  proControl: { render: () => `<div style="display:flex;gap:.6rem;flex-wrap:wrap;align-items:center">${controlHtml({ type: 'select', options: [{ value: 'a', label: 'Option A' }, { value: 'b', label: 'Option B' }] } as never, 'a' as never, '')}${controlHtml({ type: 'number' } as never, 42 as never, '')}</div>` },
  validSteps: { render: () => stepsHtml({ history: [
    { action: 'c2pa.created', when: '2026-07-01T09:00:00Z', softwareAgent: 'Lolly', digitalSourceType: 'http://cv.iptc.org/newscodes/digitalsourcetype/digitalCreation' },
    { action: 'c2pa.color_adjustments', when: '2026-07-02T11:00:00Z', softwareAgent: 'Adobe Photoshop' },
  ] } as never) },
  validInputs: { render: () => inputsDigestHtml({ Background: '#1a1a2e', Headline: 'Ship it', Size: '1080×1080' }) },
};

// ── Recommendations — mirrored from plans/component-audit.md ────────────────────
interface Rec { title: string; severity: 'high' | 'medium' | 'low'; problem: string; fix: string }
const RECOMMENDATIONS: Rec[] = [
  { title: `Collapse five segmented-control systems into one (.view-seg) with one active convention`, severity: "high", problem: `The same pill/segment button group is implemented 5+ times: .view-seg/.view-seg-btn (canonical, aria-pressed, gallery.css:508), .segmented-control/.segmented-btn (storage.css:350, aria-pressed duplicate), .dash-tabs/.dash-tab (dashboard.css:40, .is-active), .color-mode-tabs/.color-mode-tab (components.css:349, aria-selected), and .be-stored-seg (brand-editor.ts:802, bespoke aria-pressed that pointedly does not reuse .view-seg). Plus .view-toggle-opt and .profile-menu-seg. Three active-state conventions coexist for one job.`, fix: `Make .view-seg + segHtml() the sole segmented primitive; standardize on aria-pressed; delete .segmented-control and .be-stored-seg; re-skin .dash-tabs/.color-mode-tabs as variants; unify the roving-tabindex JS.` },
  { title: `Introduce a real .btn base and retire the ~10 hand-rolled primary-fill buttons`, severity: "high", problem: `The primary-fill recipe (background:hsl(var(--primary));color:hsl(var(--primary-foreground))) is re-typed with no base class in .be-cta, .share-copy-btn, .toast-action, .unsaved-save, .gallery-pill.active, .plat-pill, .plat-swatch-chip, .pro-btn--primary, .projects-confirm-primary, .dash-hero-cta, .neuro-show-btn. The generic button class is itself inconsistent: .btn vs .pro-btn vs bare .save-btn/.copy-btn; Save appears as .save-btn, .render-pill-save, .pro-sess-save and data-me-saveall.`, fix: `Ship .btn/.btn--primary/.btn--ghost/.btn--danger/.btn--sm in parts/buttons.css; map .be-cta→.btn--primary, .be-btn→.btn--ghost; alias .pro-btn/.profile-btn-primary/.cat-dl-go during migration.` },
  { title: `Establish chip/pill naming rules and merge the byte-identical ones`, severity: "high", problem: `'Rounded label' is spelled chip/pill/tag/badge/stat interchangeably: .plat-chip, .plat-pill, .dash-chip, .cat-tag, .be-ps-chip, .genai-pill, .lolly-badge, .plat-stat, .store-chip, .tile-badge, .plat-chip-flag, .cat-group-count, .plat-ramp-count. .cat-group-count and .plat-ramp-count are byte-for-byte identical (999px/--muted/.7rem/600). .gtile-iconfill and .ftile-iconfill are likewise identical under two prefixes.`, fix: `Define one .chip primitive with --count/--flag/--status modifiers; keep brand-independent provenance lockups (.genai-pill, .lolly-badge) as named pills on the same box; merge the identical count bubble and iconfill tracer immediately.` },
  { title: `Ship one modal primitive; stop hand-rolling <dialog> lifecycle`, severity: "high", problem: `The native-<dialog> open/Escape/backdrop-hit-test/body-mount/focus-first sequence is reimplemented in confirm-dialog.ts, share-dialog.ts, welcome-dialog.ts, gallery meta/history dialogs, catalog details/download/crop dialogs, projects toolpicker/movepicker/name-prompt, and profile.ts uses body-level overlay divs (.clear-dialog-overlay, .userimg-lightbox-overlay) that re-trap focus by hand ~4x.`, fix: `Promote confirm-dialog.ts's chrome into mountModal(content, opts) owning lifecycle+focus-trap; refactor share/welcome/gallery/catalog/projects/profile onto it. Rename the app-wide .projects-confirm prefix to .modal-*.` },
  { title: `Create a shared icon registry`, severity: "high", problem: `Inline Lucide SVG maps live in at least seven files: category-icons.ts, catalog-summary.ts (palette/film-strip glyphs duplicated near-verbatim), recording-tips.ts, gallery.ts consts, valid.ts (30+ ICONS), projects.ts (~10), folder-tiles.ts, profile.ts. The '?' help glyph is redefined in footer-nav/featured-row/help-tip; the chevron in ≥4 places; the NEURO glyph in both sound-toggle and neuro-dock.`, fix: `One lib/icons.ts exporting icon(name,size) over a single path registry; delete the per-file maps.` },
  { title: `One saved-session row primitive`, severity: "high", problem: `The same saved-session object (thumb+label+tool+time+bytes, plus batch variant) is rendered by three disjoint class trees: sessionTile() (folder-tiles.ts:142, .folder-tile/.tile-*), .saved-row (gallery.ts:1903), and .store-sess (profile.ts:589). profile.ts also carries a local fmtBytes that re-implements the canonical lib/format.ts one.`, fix: `Unify on one row/tile component with a layout:'tile'|'row' switch, homed in folder-tiles.ts (it owns the canonical badges + fmtBytes); delete gallery .saved-row and profile .store-sess builders and the duplicate fmtBytes.` },
  { title: `One disclosure/fold primitive for all <details> cards`, severity: "medium", problem: `.plat-section is canonical and dashboard reuses it via .dash-collapse, but the studio ships .be-subst-details, profile ships .profile-collapse, tool inputs ship .input-section, and the export panel ships four bespoke disclosure cards (.export-cmyk/.export-pdfpass/.export-c2pa/.export-print) with identical icon-head+body+hint anatomy but separate class names.`, fix: `One .section-card/.disclosure with a hint slot; make the four export cards variants and re-skin .be-subst-details/.profile-collapse/.input-section onto the same base.` },
  { title: `One zoom HUD`, severity: "medium", problem: `The −/percent/+/Fit canvas control is implemented three times with different markup, icons and disabled-state logic: .stage-nav (tool-stage-nav.ts), .me-zoom (multi-edit.ts), .pro-zoom (pro/index.ts); plus a fourth .cat-zoom-hud in the catalog details modal.`, fix: `Extract mountZoomHud(target,{onFit,extras}) (the tool version already accepts toggle slots) and reuse in multi-edit, pro and catalog details.` },
  { title: `Consolidate the four HTML escapers, NAV_EVENTS, and the body-popover lifecycle`, severity: "medium", problem: `escapeHtml (lib/html.ts), escape (utils.ts), and private esc() in help-tip.ts and recording-tips.ts all do one job. NAV_EVENTS is redeclared in lang-menu, profile-menu and welcome-dialog. lang-menu and profile-menu duplicate position()/close()/trapFocus/teardown; projects vs folder-overlay duplicate a context-menu popover again.`, fix: `One exported escape imported everywhere; one exported NAV_EVENTS + a shared mountBodyPopover() helper.` },
  { title: `One card/panel surface + one section-header primitive`, severity: "medium", problem: `.plat-section, .dash-card, .be-panel, .profile-card, .plat-client-card/.plat-font/.plat-theme/.cap-card, and .cat-tile all restate --card|--background + border + radius. Header blocks repeat three ways: .plat-header/.plat-title, .start-head/.start-title/.start-eyebrow, .be-panel-head/.be-panel-title/.be-panel-sub.`, fix: `One .card surface and one .section-header (title/eyebrow/sub) primitive; .plat-section is the natural canonical base.` },
  { title: `Unify the gallery/catalog topbar and search-clear that are hand-duplicated`, severity: "medium", problem: `The .gallery-topbar + .gallery-topright + .profile-link + filter/view popover cluster is near-identical between gallery.ts and catalog.ts but hand-copied. Search-clear is split too: gallery mints .gallery-search-clear with inline JS styles while catalog reuses projects' .projects-search-clear.`, fix: `Extract mountViewTopbar({right}) and a single search-box component (footer-nav already exports gallerySearchBox; give it the clear button). Featured-row is the model — one mount serves 3 views.` },
  { title: `Fold the swatch-tile trio and de-duplicate the theme-persist block`, severity: "medium", problem: `The same PaletteEntry is drawn four ways: read-only .plat-swatch, editable .be-swatch, mobile .stu-chip, and the palette-wheel dot. Separately the theme control is reimplemented ~4x (createThemeToggle, themeSegmentHtml/.view-seg, profile-menu theme group, profile Appearance cards), each copy-pasting host.profile.get()→set({...profile,theme})+playThemeSfx().`, fix: `One swatchTile(entry,{editable}) and a setTheme(host,theme) helper all four theme UIs call.` },
  { title: `Low-severity batchable cleanups`, severity: "low", problem: `Custom axis sliders .color-lch-slider and .color-mode-slider duplicate thumb rules; the mono text-input recipe repeats across .be-fmt-input/.be-lock-field/.be-cmyk-in/.share-link-field/.color-input; note boxes .plat-note/.error/.share-note/.valid-note are near-identical; the progress toast is one component under two names; sound-toggle keeps dead soundSegmentHtml aliases; the 'i' tooltip exists three ways; activity-summary classes are styled twice.`, fix: `Batch: shared slider thumb rules; a .field-input; one .note callout; one toast with modifiers; delete dead aliases; route all 'i' tooltips through helpTip; move .activity-* to one stylesheet.` },
];

// ── Render ─────────────────────────────────────────────────────────────────────
const sevLabel = (s: Rec['severity']): string => s === 'high' ? t('unify') : s === 'medium' ? t('tidy') : t('note');

function recHtml(r: Rec): string {
  return `<div class="cl-rec">
    <div class="cl-rec-top"><span class="cl-sev cl-sev--${r.severity}">${escape(sevLabel(r.severity))}</span><span class="cl-rec-title">${escape(r.title)}</span></div>
    <p class="cl-rec-body">${escape(r.problem)} <span class="cl-rec-fix">→ ${escape(r.fix)}</span></p>
  </div>`;
}

// How a specimen is actually shown — not its nature, but what the card displays,
// so the tag never says "live" over a source snippet. Live = rendered by a LIVE
// renderer; sample = static markup; source = a host-bound call shown as code.
type Mode = 'live' | 'sample' | 'source';
function renderMode(s: Specimen): Mode {
  if (s.live && LIVE[s.live]) return 'live';
  if (s.markup) return 'sample';
  return 'source';
}
const MODE_LABEL: Record<Mode, string> = { live: 'live', sample: 'sample', source: 'source' };

function specimenShell(s: Specimen, idx: number): string {
  const mode = renderMode(s);
  // Colour tools + wide media get more room; everything else fits the auto grid.
  const wide = s.live === 'colorField' || s.live === 'footerNav';
  const tall = s.live === 'colorField' || s.live === 'wheel';
  const plain = mode === 'source' || (!!s.live && s.live !== 'genai' && s.live !== 'lollyBadge' && s.live !== 'tileBadges');
  const cls = ['cl-card', wide ? 'cl-card--wide' : '', tall ? 'cl-card--tall' : ''].filter(Boolean).join(' ');
  const stageCls = ['cl-stage', plain ? 'cl-stage--plain' : ''].filter(Boolean).join(' ');
  const eg = s.eg?.length ? `<div class="cl-eg">${s.eg.map(e => `<span>${escape(e)}</span>`).join('')}</div>` : '';
  const kindTag = `<span class="cl-kind cl-kind--${mode === 'sample' ? 'css' : mode === 'source' ? 'host' : 'live'}">${escape(MODE_LABEL[mode])}</span>`;
  return `<div class="${cls}">
    <div class="${stageCls}" data-cl-stage="${idx}"></div>
    <div class="cl-meta">
      <div class="cl-name">${escape(s.name)} ${kindTag}</div>
      ${s.description ? `<p class="cl-desc">${escape(s.description)}</p>` : ''}
      ${s.defined ? `<p class="cl-src">${escape(s.defined)}</p>` : ''}
      ${eg}
    </div>
  </div>`;
}

const sectionId = (title: string): string => 'cl-' + title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// A `<dialog>` renders in the browser's top layer, which escapes the stage's
// `contain` — a markup sample with a bare <dialog> would cover the whole page.
// Reduce it to an in-flow element (its own classes still style the chrome) so it
// previews as a contained card. Overlays that merely use `position: fixed` are
// already trapped by the stage's containment and need no help.
function neutralizeMarkup(html: string): string {
  return html.replace(/<dialog\b/gi, '<div data-cl-dialog').replace(/<\/dialog>/gi, '</div>');
}

export async function mountComponents(viewEl: HTMLElement, _host: HostV1, cameFromApp: boolean): Promise<void> {
  document.title = 'Components — Lolly';
  viewEl.classList.add('cl-view', 'components-view');

  // A flat, ordered list of every specimen with the section it belongs to — so the
  // stage-fill loop can address each by index without re-walking the tree.
  const flat: Specimen[] = AUDIT_SECTIONS.flatMap(sec => sec.items);
  let n = 0;
  const jump = AUDIT_SECTIONS.map(sec => `<a href="#${sectionId(sec.title)}">${escape(sec.title)}</a>`).join('');

  viewEl.innerHTML = `
    <header class="cl-head">
      <button type="button" class="tools-home cl-back" data-cl-back>${escape(cameFromApp ? t('Back') : t('Tools'))}</button>
      <h1 class="cl-title">${escape(t('Component library'))}</h1>
      <p class="cl-sub">${escape(t('Live samples of the shell’s components — common primitives first, then by view. Full inventory and unification notes: plans/component-audit.md.'))}</p>
      <nav class="cl-jump" aria-label="${escape(t('Jump to section'))}">${jump}</nav>
    </header>

    <section class="cl-recs" aria-label="${escape(t('Recommendations'))}">
      <h2>${escape(t('Recommendations — what to unify'))}</h2>
      <p class="cl-recs-lede">${escape(t('The headline finding: there is no shared primitive layer — the same atoms are re-built per view under different class prefixes. Ranked by blast radius.'))}</p>
      ${RECOMMENDATIONS.map(recHtml).join('')}
    </section>

    ${AUDIT_SECTIONS.map(sec => `
      <section class="cl-section" id="${sectionId(sec.title)}">
        <div class="cl-section-head">
          <h2>${escape(sec.title)}</h2>
          <span class="cl-section-kind">${sec.group === 'common' ? escape(t('common')) : escape(t('view'))}</span>
        </div>
        ${sec.blurb ? `<p class="cl-sub" style="margin-top:-.5rem">${escape(sec.blurb)}</p>` : ''}
        <div class="cl-grid">
          ${sec.items.map(item => specimenShell(item, n++)).join('')}
        </div>
      </section>`).join('')}
  `;

  // Fill each stage. A live component renders through its LIVE renderer; a markup
  // specimen drops in its sample; a host-bound one shows its source snippet. Any
  // throw shows the error rather than a silent empty box — this is a component
  // surface; failures are the point of looking.
  flat.forEach((item, i) => {
    const stage = viewEl.querySelector<HTMLElement>(`[data-cl-stage="${i}"]`);
    if (!stage) return;
    try {
      if (item.live && LIVE[item.live]) {
        const spec = LIVE[item.live]!;
        const out = spec.render();
        if (typeof out === 'string') stage.innerHTML = out;
        else stage.appendChild(out);
        spec.wire?.(stage);
      } else if (item.markup) {
        stage.innerHTML = neutralizeMarkup(item.markup);
      } else if (item.code) {
        // Needs the host bridge to run — show the call as a source snippet.
        stage.classList.add('cl-stage--plain');
        stage.innerHTML = `<code class="cl-code">${escape(item.code)}</code>`;
      } else {
        stage.innerHTML = `<span class="cl-broken">no sample</span>`;
      }
    } catch (err) {
      stage.innerHTML = `<span class="cl-broken">render failed: ${escape(String((err as Error)?.message ?? err))}</span>`;
    }
  });

  // The one nav affordance. In-app arrival → step back to where you were; a cold
  // deep link (no in-app predecessor) → the gallery.
  viewEl.querySelector<HTMLButtonElement>('[data-cl-back]')?.addEventListener('click', (e) => {
    e.preventDefault();
    if (cameFromApp && window.history.length > 1) window.history.back();
    else window.location.hash = '#/';
  });

  armViewEnter(viewEl, '.cl-head, .cl-recs, .cl-section');
}
