// SPDX-License-Identifier: MPL-2.0
/**
 * SPA i18n runtime — a tiny t() catalog lookup, no framework.
 *
 * English is the key: t('Save Profile') renders literally in English builds,
 * and as an identity fallback for any string not yet translated (or not yet
 * wrapped in t() at all) — the app never breaks, it just shows English. Locale
 * catalogs are flat { "English string": "translated string" } JSON files under
 * ./locales, generated by scripts/translate.ts, loaded as one dynamic-import
 * chunk per language so English users (the default) pay zero extra bytes.
 *
 * Preference storage mirrors theme.ts exactly: canonical on `profile.lang`,
 * mirrored to `localStorage 'lang'` for the pre-paint <html lang> read (see the
 * inline script in index.html), reconciled from the profile in main.ts's boot().
 */

import { LANGS, LANG_META, normalizeLang } from '@lolly/engine';
import type { Lang } from '@lolly/engine';

export { LANGS, LANG_META, normalizeLang };
export type { Lang };

/**
 * The language-switcher indicator icon (~/Build/language-icon.svg), inlined so
 * it can sit next to any picker with `fill="currentColor"` picking up the
 * surrounding text colour — no network request, themes automatically. Kept as
 * one constant so every picker (welcome dialog, profile card) renders the same
 * mark; the docs/build.ts landing-site nav duplicates this same markup since it
 * has no shared import path with the SPA (see its own LANG_ICON_SVG).
 */
export const LANG_ICON_SVG = '<svg class="lang-switch-icon" viewBox="0 0 440.332 510.236" fill="currentColor" aria-hidden="true"><path d="m311.768 445.719 12.531 20.615c-31.404 20.067-66.19 30.034-103.148 33.127h-16.436c-3.287 0-19.54-2.008-20.088-2.008-6.026-.913-12.235-2.009-17.896-3.287q-15.34-3.562-30.68-9.315c-7.487-2.739-15.34-6.391-22.28-9.86-3.469-1.644-6.573-3.287-9.86-5.296-1.096-.548-6.94-4.748-9.862-4.748-3.287 0-5.297 2.556-5.297 5.295 0 1.644.184 3.106 2.375 4.566 12.418 8.218 25.566 14.426 38.166 19.174 6.94 2.74 14.063 5.296 21.367 7.305 4.2 1.278 8.948 2.558 13.33 3.47 5.662 1.279 11.689 2.375 17.35 3.288 6.392.913 13.15 1.643 19.541 2.191 36.8 0 80.597-5.566 122.537-30.498 1.721-1.243 4.493-2.286 6.744-3.758l11.428 18.801 15.725-45.576z"/><path d="m639.838 180.403-40.768-12.976V48.363c0-3.47-2.557-5.843-5.844-5.843-2.556 0-84.917 28.306-91.492 30.68-22.334 7.444-86.798 29.733-86.798 29.733-1.034.297-2.638.787-4.741 1.449L252.855 48.85a1.826 1.826 0 0 0-2.435 1.722v106.724c-24.405 8.17-41.808 14.02-42.701 14.335-1.644.548-4.2.913-5.662 2.922-.73.73-.913 2.009-1.278 2.922v306.982c0 .365.183.547.183.73 1.095 2.374 3.104 3.835 5.296 3.835 2.739 0 208.367-69.03 212.933-70.856.215-.072.458-.24.697-.438L638.73 487.48a1.826 1.826 0 0 0 2.38-1.74V182.143c0-.795-.514-1.5-1.272-1.74M410.973 409.4l-199.054 66.29V182.04l199.054-66.29ZM587.93 55.668v108.213l-164.492-52.354Zm-20.243 329.6-10.52-38.43-60.517-18.341-13.013 31.304-29.292-8.886 62.178-152.587 28.508 8.636 51.939 187.188zm-183.723-51.715c-1.658-.602-35.965-14.814-40.828-17.142-3.98-1.914-13.737-6.04-18.328-7.913 12.931-19.938 21.094-34.984 22.18-37.276 2.012-4.193 15.699-30.976 16.018-32.625.31-1.67.7-7.843.399-9.31-.302-1.495-5.32 1.38-12.134 3.69-6.824 2.3-19.794 10.735-24.803 11.793-5.027 1.048-21.094 7.135-29.316 9.863s-23.773 7.475-30.17 9.202c-6.406 1.728-11.998 1.865-15.581 2.951 0 0 .477 5.019 1.428 6.523.94 1.505 4.33 5.194 8.27 6.224 3.942 1.037 10.465.62 13.436-.058 2.97-.69 8.114-3.204 8.804-4.301.698-1.116-.36-4.553.814-5.592 1.186-1.028 16.843-4.688 22.755-6.474 5.911-1.817 28.54-9.61 31.607-9.213-.971 3.223-19.173 39.276-25.035 50.032-5.864 10.755-39.926 58.07-47.177 66.408-5.505 6.338-18.843 22.558-23.463 26.218 1.165.322 9.425-.387 10.93-1.318 9.377-5.777 24.996-25.22 30.026-31.142 14.949-17.532 28.083-35.947 38.497-51.75h.011c2.03.845 18.434 14.21 22.714 17.173 4.281 2.96 21.173 12.385 24.833 13.948 3.66 1.583 17.725 8.068 18.317 5.873.591-2.213-2.544-15.154-4.204-15.784m-106.167-120.33c-1.118-1.098 1.455 8.968 5.036 12.59 6.35 6.405 11.31 7.23 13.95 7.337 5.844.233 13.056-1.456 17.338-3.25 4.144-1.769 11.405-5.476 14.153-10.883.583-1.156 2.173-3.097 1.174-7.893-.757-3.689-3.106-4.98-5.97-4.775-2.863.193-11.532 2.505-15.725 3.794-4.194 1.273-12.834 3.903-16.6 4.72-3.756.814-12.038-.379-13.356-1.64" transform="translate(-200.78 -42.52)"/><path d="m529.556 247.883-21.718 52.496 39.929 12.104z" transform="translate(-200.78 -42.52)"/></svg>';

type NonEnglishLang = Exclude<Lang, 'en'>;

const LOADERS: Record<NonEnglishLang, () => Promise<{ default: Record<string, string> }>> = {
  es: () => import('./locales/es.json'),
  de: () => import('./locales/de.json'),
  fr: () => import('./locales/fr.json'),
  zh: () => import('./locales/zh.json'),
  ja: () => import('./locales/ja.json'),
  vi: () => import('./locales/vi.json'),
  pt: () => import('./locales/pt.json'),
  'zh-hant': () => import('./locales/zh-hant.json'),
  cs: () => import('./locales/cs.json'),
  nl: () => import('./locales/nl.json'),
  tl: () => import('./locales/tl.json'),
  sv: () => import('./locales/sv.json'),
  ms: () => import('./locales/ms.json'),
  ro: () => import('./locales/ro.json'),
};

let active: Lang = 'en';
let catalog: Record<string, string> = {};
const listeners = new Set<(lang: Lang) => void>();

/** The active language code. */
export function currentLang(): Lang {
  return active;
}

/** Native-name options for a picker, English first. */
export function langOptions(): Array<{ code: Lang; nativeName: string }> {
  return LANGS.map(code => ({ code, nativeName: LANG_META[code].nativeName }));
}

/**
 * Resolve + load the boot-time language: an explicit override (the `lang` URL
 * param, applies for this session only) beats the saved profile, which beats
 * the localStorage mirror, which beats the browser's own language, which beats
 * English. Called once from main.ts's boot(), before the first view renders.
 */
export async function initI18n(opts: { urlLang?: string | null; profileLang?: string | null } = {}): Promise<Lang> {
  const fromUrl      = normalizeLang(opts.urlLang);
  const fromProfile  = normalizeLang(opts.profileLang);
  const fromStorage  = normalizeLang(localStorage.getItem('lang'));
  const fromBrowser  = normalizeLang(navigator.language?.split('-')[0]);
  const lang = fromUrl ?? fromProfile ?? fromStorage ?? fromBrowser ?? 'en';
  await setActiveLang(lang, { persist: false });
  return lang;
}

/**
 * Switch the active language: loads its catalog, updates <html lang>, and (from
 * a picker) mirrors to localStorage. Callers that also want to persist to the
 * profile do so themselves via host.profile.set — this module only owns the
 * in-memory catalog + localStorage mirror, matching theme.ts's applyTheme.
 */
export async function setActiveLang(lang: Lang, opts: { persist?: boolean } = {}): Promise<void> {
  active = lang;
  catalog = lang === 'en' ? {} : (await LOADERS[lang]().catch(() => ({ default: {} }))).default;
  document.documentElement.lang = LANG_META[lang].htmlLang;
  if (opts.persist) localStorage.setItem('lang', lang);
  listeners.forEach(fn => { try { fn(lang); } catch (e) { console.error(e); } });
}

/** Notified after a language switch completes (catalog loaded, <html lang> set). */
export function onLangChange(fn: (lang: Lang) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

/** The slice of the host bridge a language picker needs to persist its choice. */
export interface LangSwitchHost {
  profile: { get(): Promise<object>; set?(profile: object): Promise<unknown> };
}

/**
 * Switch the active language from a picker: persists to profile.lang (dropped
 * entirely for 'en', matching the profile view's original behaviour), then
 * reloads so the whole app — not just the caller's own wave-1-wrapped strings —
 * re-renders in the new language. Shared by the profile card's picker and the
 * gallery/catalog/projects lang-fab menu.
 */
export async function switchLang(host: LangSwitchHost, next: Lang): Promise<void> {
  if (next === currentLang()) return;
  try {
    const current = await host.profile.get();
    const { lang: _drop, ...rest } = current as Record<string, unknown>;
    await host.profile.set?.(next === 'en' ? rest : { ...rest, lang: next });
  } catch { /* preference save is best-effort — the switch below still applies for this session */ }
  await setActiveLang(next, { persist: true });
  window.location.reload();
}

/**
 * URL for a docs (/info) page in the currently active app language. English is
 * unprefixed (`/info/<slug>.html`); every other locale lives under
 * `/info/<lang>/<slug>.html` — mirrors docs/build.ts's localeHref exactly
 * (duplicated, not imported: that's a static-site generator with no shared
 * module boundary with this SPA — see its own copy right next to
 * LANG_ICON_SVG). `slug` is 'index' for the docs homepage — ALWAYS keep the
 * explicit `index.html` filename here (never shorten to a bare `/info/` or
 * `/info/<lang>/` directory URL): the dev server's static-file middleware
 * (shells/web/vite.config.js's serveRepoStatic) only resolves a bare
 * directory to index.html for the literal `/info`/`/info/` root, not for a
 * `/info/<lang>/` subpath — an omitted filename there 404s through to the
 * SPA fallback instead of the docs page.
 */
export function docsHref(slug: string): string {
  const lang = currentLang();
  const file = slug === 'index' ? 'index.html' : `${slug}.html`;
  return lang === 'en' ? `/info/${file}` : `/info/${lang}/${file}`;
}

/**
 * Translate a UI string. The English source doubles as the lookup key, so an
 * untranslated (or not-yet-wrapped) string simply renders as English instead of
 * breaking. `params` does plain {name} interpolation.
 */
export function t(source: string, params?: Record<string, string | number>): string {
  let out = catalog[source] ?? source;
  if (params) {
    for (const [key, value] of Object.entries(params)) out = out.replaceAll(`{${key}}`, String(value));
  }
  return out;
}
