// SPDX-License-Identifier: MPL-2.0
/**
 * SPA i18n runtime — a tiny t() catalog lookup, no framework.
 *
 * English is the key: t('Save Profile') renders literally in English builds,
 * and as an identity fallback for any string not yet translated (or not yet
 * wrapped in t() at all) — the app never breaks, it just shows English. Locale
 * catalogs are flat { "English string": "translated string" } JSON files under
 * ./locales, generated by scripts/translate.ts, loaded as one dynamic-import
 * chunk per language so English users (the default) pay zero extra bytes.
 *
 * Preference storage mirrors theme.ts exactly: canonical on `profile.lang`,
 * mirrored to `localStorage 'lang'` for the pre-paint <html lang> read (see the
 * inline script in index.html), reconciled from the profile in main.ts's boot().
 */

import { LANGS, LANG_META, normalizeLang } from '@lolly/engine';
import type { Lang } from '@lolly/engine';

export { LANGS, LANG_META, normalizeLang };
export type { Lang };

type NonEnglishLang = Exclude<Lang, 'en'>;

const LOADERS: Record<NonEnglishLang, () => Promise<{ default: Record<string, string> }>> = {
  es: () => import('./locales/es.json'),
  de: () => import('./locales/de.json'),
  fr: () => import('./locales/fr.json'),
  zh: () => import('./locales/zh.json'),
  ja: () => import('./locales/ja.json'),
  vi: () => import('./locales/vi.json'),
};

let active: Lang = 'en';
let catalog: Record<string, string> = {};
const listeners = new Set<(lang: Lang) => void>();

/** The active language code. */
export function currentLang(): Lang {
  return active;
}

/** Native-name options for a picker, English first. */
export function langOptions(): Array<{ code: Lang; nativeName: string }> {
  return LANGS.map(code => ({ code, nativeName: LANG_META[code].nativeName }));
}

/**
 * Resolve + load the boot-time language: an explicit override (the `lang` URL
 * param, applies for this session only) beats the saved profile, which beats
 * the localStorage mirror, which beats the browser's own language, which beats
 * English. Called once from main.ts's boot(), before the first view renders.
 */
export async function initI18n(opts: { urlLang?: string | null; profileLang?: string | null } = {}): Promise<Lang> {
  const fromUrl      = normalizeLang(opts.urlLang);
  const fromProfile  = normalizeLang(opts.profileLang);
  const fromStorage  = normalizeLang(localStorage.getItem('lang'));
  const fromBrowser  = normalizeLang(navigator.language?.split('-')[0]);
  const lang = fromUrl ?? fromProfile ?? fromStorage ?? fromBrowser ?? 'en';
  await setActiveLang(lang, { persist: false });
  return lang;
}

/**
 * Switch the active language: loads its catalog, updates <html lang>, and (from
 * a picker) mirrors to localStorage. Callers that also want to persist to the
 * profile do so themselves via host.profile.set — this module only owns the
 * in-memory catalog + localStorage mirror, matching theme.ts's applyTheme.
 */
export async function setActiveLang(lang: Lang, opts: { persist?: boolean } = {}): Promise<void> {
  active = lang;
  catalog = lang === 'en' ? {} : (await LOADERS[lang]().catch(() => ({ default: {} }))).default;
  document.documentElement.lang = LANG_META[lang].htmlLang;
  if (opts.persist) localStorage.setItem('lang', lang);
  listeners.forEach(fn => { try { fn(lang); } catch (e) { console.error(e); } });
}

/** Notified after a language switch completes (catalog loaded, <html lang> set). */
export function onLangChange(fn: (lang: Lang) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

/**
 * Translate a UI string. The English source doubles as the lookup key, so an
 * untranslated (or not-yet-wrapped) string simply renders as English instead of
 * breaking. `params` does plain {name} interpolation.
 */
export function t(source: string, params?: Record<string, string | number>): string {
  let out = catalog[source] ?? source;
  if (params) {
    for (const [key, value] of Object.entries(params)) out = out.replaceAll(`{${key}}`, String(value));
  }
  return out;
}
